### ISSUE TITLE
fastbootDependencies are not respected (causing failure with in-repo addons)

### ISSUE THREAD

**Issue by mehulkar** [embroider-build/embroider#1158]
When building with `ember-cli-fastboot@2` and `@embroider/*@1.5`, I'm seeing that `dist/package.json` includes dependencies that are not in the `fastbootDependencies` list in `./package.json`. 

While this could be problematic on its own, it also causes a build failure, because it includes in-repo addons in this list also. Because these in-repo addons are not in the npm registry (or could be totally different packages), this can:

1. break the fastboot server build
2. be a security risk(?) since an in-repo addon that is named the same as something else published to npm can get installed.

Here's a repro where I show that an in-repo addon named with a `@scope` causes the fastboot server build to fail: https://github.com/mehulkar/embroider-in-repo-addons

(Reproduces with `ember-cli-fastboot@3.2` as well)

**Comment by ef4** [comment]
While I am not opposed to getting closer to the classic behavior here if people want to work on it, I think it's not a good behavior and you'll have a much nicer time if you stop doing a separate NPM install for fastboot.

The straightforward way to consume any dependency from NPM is to import it. If you only import it into a fastboot-specific file, it will only be included in a fastboot-specific output chunk. 

All the customized machinery for managing fastboot dependencies differently than other dependencies isn't needed. It was only needed originally because Ember apps couldn't import from NPM and couldn't analyze which of their files was consuming which NPM package. Embroider has all of that and works fine when using some NPM packages in the browser and others in fastboot.

We support the traditional "/fastboot" directory as a way to override files from "/app". If you import a dependency from NPM there, it will get built into `dist`. 

Alternatively`@embroider/macros` can also switch fastboot-vs-browser and in production builds will produce optimized separate output for each:


```js
import { macroCondition, getGlobalConfig, importSync } from '@embroider/macros';

let implementation;
if (getGlobalConfig().fastboot?.isRunning()) {
  implementation = importSync('some-node-polyfill');
} else {
  implementation = importSync('some-browser-thing');
}
```

Internally, if you have the same file name in both `/fastboot` and `/app` Embroider compiles that to something like the macros example above.

**Comment by mehulkar** [comment]
Maybe I’m misunderstanding… if I don’t install dependencies, how do I run my prod server? is the idea to use ./package.json and ignore dist/package.json?

**Comment by ef4** [comment]
Yes, you could do it that way, or you could have a separate prod server application with its own package.json (since there's pretty much zero overlap between the dependencies needed to build the ember app and the dependencies needed by a production fastboot server). I have seen people make a `/srv` directory within their app's repo to hold this.

The idea is that the fastboot server -- not unlike a browser -- should be pretty agnostic to the exact version of your app that it's going to run. When you deploy a new build of the app, both browsers and fastboot servers will download the new build and run it. It should only rarely be necessary to the deploy the fastboot servers -- normal app releases shouldn't require a server deploy.

I think this is already a somewhat common architecture, given the existence of https://github.com/ember-fastboot/fastboot-s3-notifier and https://github.com/ember-fastboot/fastboot-s3-downloader, which expect to work this way.

Of course it's also OK to deploy the fastboot servers for every build, basically hard-coding the built ember app into them. But even in that case, it's pretty clean to keep the dedicated server code separate in its own application with its own package.json.

**Comment by mehulkar** [comment]
That makes sense. Would it make sense not to generate a `dist/package.json` under embroider then? It's already doing something different, so maybe we could be more explicit about the known good pattern? (and maybe document it somewhere in embroider if it's a transition path other users may run into)

**Comment by ef4** [comment]
It would make sense to eventually drop the package.json. Right now there are still things fastboot reads from it.

**Comment by void-mAlex** [comment]
hello @mehulkar the question here seems to be answered, could we close this and open a separate ticket specifically regarding documentation? that would at least be more helpful than the title of this one

**Comment by mehulkar** [comment]
Sure, I can close this
