### ISSUE TITLE
Should `/app/config/environment.js` be an exception when defining `staticAppPaths: ['config']`?

### ISSUE THREAD

**Issue by bertdeblock** [embroider-build/embroider#1162]
In most of our apps, we have the habit of putting runtime config files in an `/app/config` folder.
These files are never resolved and only imported.
I wanted to ensure this by defining `staticAppPaths: ['config']`,
but it seems that breaks resolving the magic `/app/config/environment.js` file.
Should an exception be made for this file?

**Comment by ef4** [comment]
By the time we pass the app to webpack, `config/environment.js` isn't magic anymore. It's just another file. So I *think* that's not really causing your problem.

Rather, it sounds like some code is trying to `require('APP-NAME/config/environment')` at runtime. Addons often do this, since they can't really import it statically, because that would be going "backwards" in terms of dependencies (a library importing from the app).

But this is in direct contradiction with `staticAppPaths: ['config']`. Not every file in 'config' is only statically imported if  `config/environment.js` is required at runtime. So I don't think you can set `config` to static unless you can eliminate all runtime usage of `config/environment.js`.

As an alternative, you can keep `config` static but do your own runtime registration of the one file that isn't static, like:

```js
// app.js
import ENV from './config/environment';
window.define('MY-APP/config/environment', function() { return ENV });
```

Or you can move your static files out of `config` to a different directory so that one can be purely static and leave `config` to have its backward-compatible behavior.

**Comment by bertdeblock** [comment]
By `require('APP-NAME/config/environment')`, do you mean, doing a lookup via the owner?
If so, eliminating all those cases simply because a single person wants 
to use a static `config` folder seems a bit much probably 😄.

I think I'm going to leave it as is, though I do feel it would be nice if this were possible.
`import config from 'module-prefix/config/environment';` has always felt a bit weird 
because `/app/config/environment.js` doesn't really exist.

Maybe it would be nice if somewhere in the future we could have a util
for getting your app's config?

```js
import { getConfig } from '@ember/...';

getConfig();
```

`/app/config/environment.js` could become something completely random
that the user doesn't have to know about?

But I'm getting a bit off track here.

Thanks for the explanation!
Feel free to close this if you think this is a non-issue.

**Comment by ef4** [comment]
> Maybe it would be nice if somewhere in the future we could have a util
for getting your app's config?

Yeah, the intended replacement is `import { getOwnConfig } from '@embroider/macros'`.

**Comment by bertdeblock** [comment]
For apps, the config for `import { getOwnConfig } from '@embroider/macros'` 
needs to be put in the `ember-cli-build.js` file. Does that mean that at some point, 
`/config/environment.js` won't be a thing anymore?

**Comment by ef4** [comment]
Maybe, but it would all depend on what happens in a "v2 app format" RFC. I think ember-cli-build.js itself would also see significant changes in such a design.

**Comment by bertdeblock** [comment]
Thanks for the response, going to close this for now if that's okay.
