### ISSUE TITLE
dependencySatisfies macro has confusing semantics

### ISSUE THREAD

**Issue by ef4** [embroider-build/embroider#121]
@rwjblue pointed out that `semver.satisfies()` is not really the semantics you usually want for conditional code inclusion.

The problem is that you want to write things like 

```js
if (!semver.satisfies(emberVersion, '> 3.8')) {
  // add some polyfill
}
```

But  `semver.satisfies('3.9.0-beta.0', '> 3.8')` returns false, which was really not your intent.

`ember-dependency-helpers` solves this by exposing `gte` and `lte` instead of `satisfies`. But that is less expressive than being able to use complete semver range expressions.

We could choose to replace our `dependencySatisfies` macro with `dependencyGTE` and friends.

Alterantively, I *think* `semver.satisfies(semver.coerce(pkg.version), pattern)` has the semantics we actually want, but I'm opening this issue to get feedback on that idea.

**Comment by rwjblue** [comment]
I think coercing is probably fine, but I _vaguely_ worry about diverging behaviors between `semver.satisfies` and `dependencySatisfies`.

**Comment by ef4** [comment]
I can understand your suspicion of reusing the terminology "satisfies". 

Maybe it would help if we rename ours to `hasDependency('ember-source', '> 3.8')`?

**Comment by ef4** [comment]
Or maybe `hasPackage`, since I guess technically `ember-source` is rarely a dependency of the code that actually wants to use these macros.

**Comment by ef4** [comment]
(Thanks for your input BTW, I really appreciate it!)

**Comment by rwjblue** [comment]
@ef4 - I just took a look at this again (trying to use `@embroider/macros` instead of `ember-compatibility-helpers` for a new package) and have a few concerns:

* https://github.com/embroider-build/embroider/pull/122 only resolved this for templates, the original issue is still present for the JS version (and we now have divergent behavior between the Babel side and Glimmer side)...
* Coercing means (AFAICT) that it is impossible to ask if something is at least `3.20.0-beta.4` and have that **not** match `3.20.0-beta.1`. 

I'm falling back to `ember-compatibility-helpers` for now here, but I'd like to circle around and make that package obsolete (to aid future Embroider adoption)...
