### ISSUE TITLE
Missing helper: unique-id with embroider-optimized

### ISSUE THREAD

**Issue by jrjohnson** [embroider-build/embroider#1268]
In a fresh `ember-cli@4.8.0` addon adding `unique-id` to `application.hbs`
```hbs
{{#let (unique-id) as |templateId|}}
  <h2 id="{{templateId}}-title">Welcome to Ember</h2>
{{/let}}
```
results in `Missing helper: unique-id in templates/application.hbs` when running `ember try:one embroider-optimized`.

**Comment by Windvis** [comment]
That specific problem was fixed and released in [`@embroider/compat` v1.9.0]( https://github.com/embroider-build/embroider/releases/tag/release-2022-10-06.0
) but there is a different underlying issue here though.

`@embroider/test-setup` [uses its own version](https://github.com/embroider-build/embroider/blob/539493aca3a2bd56abed4a49a1b2cfeac1b2903b/packages/test-setup/src/index.ts#L54-L56) to install the `@embroider/compat`, `@embroider/core` and `@embroider/webpack` packages during the ember-try scenarios. This wasn't an issue before, but a [new release setup](https://github.com/embroider-build/embroider/issues/1237) has been introduced which allows all packages to be versioned independently. 

The last release didn't bump the version of `@embroider/test-setup` since it had no changes so the latest version is still v1.8.3. This means that at the moment, `@embroider/compat` v1.8.3 will be installed in the ember-try scenarios, which doesn't include the fix you need.

I'm not sure what the correct fix is exactly. Should we just use something like `^1.0.0` for the versions instead of the version of `@embroider/test-setup`? Or should the addons list the version range they need in the Ember try config?

**Comment by Windvis** [comment]
@jrjohnson As a quick workaround I think you can [modify your ember-try config](https://github.com/embroider-build/embroider/tree/main/packages/test-setup#embroidersafeembertryconfig) to something like this:

```js
embroiderSafe({
  npm: {
    devDependencies: {
      '@embroider/core': '^1.9.0' ,
      '@embroider/webpack': '^1.8.3',
      '@embroider/compat': '^1.9.0',
    },
  },
}),
embroiderOptimized({
  // same thing
})
```

That should override the versions and install the newest packages instead.

**Comment by jrjohnson** [comment]
This workaround works. Thanks @Windvis. I think having test-setup rely on anything in the major semver range makes sense. Are there reasons an addon would want to pick and test anything earlier than the current release? I can't think of any reason to do so now that all these libs are post 1.0.

**Comment by simonihmig** [comment]
Here is an attempt to fix this: https://github.com/embroider-build/embroider/pull/1328
