### ISSUE TITLE
docs: Clarify whether macros are usable by V2 Addons

### ISSUE THREAD

**Issue by runspired** [embroider-build/embroider#1275]
The RFC obviously says they are, and the need is there; however, the migration guide says to remove them from dependencies https://github.com/embroider-build/embroider/blob/main/PORTING-ADDONS-TO-V2.md#part-4-convert-addon-to-v2

is this because they only need to be a dev-dependency? or...

**Comment by ef4** [comment]
It's because they're a language extension. They're not needed as a dependency or devDependency.

It's misleading to have them as one, because they don't get any say over the version of `@embroider/macros` -- there is only one and it's governed by the app. 

(This is why the macros are intended to be a tiny kernel of functionality -- we would like them to never or rarely have any breaking changes. Higher-level API can compile to the macros and remain stable over the long term.)

**Comment by void-mAlex** [comment]
hello @runspired 
given the answer above does this issue still need to be open?
is there any more info required here?

**Comment by runspired** [comment]
It mostly does, I have questions around broader ecosystem compatibility and whether we'd want it as a peer-dep or just left as something to be understood by a plugin designed for whichever build framework was in use.
