### ISSUE TITLE
Helpers fail to resolve from .hbs.js file with embroider 2.x and static helpers

### ISSUE THREAD

**Issue by bendemboski** [embroider-build/embroider#1296]
Broken off of #1293

When building with embroider 2.x and static helpers, `<BasicDropdown>` fails to render because it fails to resolve any of its helpers (starting with `ensure-safe-component`). It looks like a template compilation problem, perhaps specific to files that end up with the `.hbs.js` extension.

[this repo](https://github.com/bendemboski/missing-helpers) demonstrates the issue, and its README describes what I've found through my investigation.

**Comment by ef4** [comment]
Thanks for the reproduction, I see the bug. When `@embroider/compat` is detecting what babel plugins are present in a v1 addon, it needs to remove any template compiler that's already present so that we can use our own. But it's failing to detect the template compiler installed by the newest ember-cli-htmlbars on new-enough ember versions.

This will be the fix, I just need to look through our test suite to see why this wasn't already being covered.

```diff
diff --git a/packages/compat/src/detect-babel-plugins.ts b/packages/compat/src/detect-babel-plugins.ts
index dbcd663e..1e65a7ba 100644
--- a/packages/compat/src/detect-babel-plugins.ts
+++ b/packages/compat/src/detect-babel-plugins.ts
@@ -76,4 +76,5 @@ const htmlbarPathMatches = [
   ['ember-cli-htmlbars', 'lib', 'require-from-worker.js'].join(sep),
   ['ember-cli-htmlbars', 'index'].join(sep),
   ['ember-cli-htmlbars', 'lib', 'require-from-worker'].join(sep),
+  ['babel-plugin-ember-template-compilation', 'src', 'node-main.js'].join(sep),
 ];
```

**Comment by ef4** [comment]
I figured out why the tests don't notice this -- it's because this case only happens if some other babel plugin is preventing ember-cli-babel from parallelizing.
