### ISSUE TITLE
Builds failing with template imports not found

### ISSUE THREAD

**Issue by vlascik** [embroider-build/embroider#1300]
After updating to 2.0.1 and 2.0.2, build keeps failing with 
```
Module not found: Error: Can't resolve './template' in '$TMPDIR\embroider\864ay1\Project\node_modules\ember-table\components\-private\scroll-indicators\component.js'
```

in `scroll-indicators\component.js` the `ember-table` is doing:
```
import layout from './template';
```
embroider creates `$TMPDIR\embroider\864ay1\Project\node_modules\ember-table\components\-private\scroll-indicators\template.hbs.js` file with content like this:

```
import { precompileTemplate } from "@ember/template-compilation";
export default precompileTemplate(" ...< actual hbs content of template.hbs> ...", {
  moduleName: "ember-table/components/-private/scroll-indicators/template.hbs"
});
```

but the file is not resolved at import. I imagine there is a problem with changes related to the babel precompilation plugin and the changed .hbs extensions somewhere?

embroider v2.0.2 on Windows, every package at latest as of now.

EDIT: after changing the import line to 
```
import layout from './template.hbs';
```
the build passed.

**Comment by ef4** [comment]
I was looking at this with @void-mAlex and we think we see the bug here. The [resolvable extensions](https://github.com/embroider-build/embroider/blob/de5b155eefeb55e36abfead2be7e2fccb39ed915/packages/compat/src/compat-app.ts#L235) list probably needs to expand `.hbs` to both `.hbs` and `.hbs.js` as fallout from the changes made in our 2.0 release.

**Comment by void-mAlex** [comment]
and now pr is up
