### ISSUE TITLE
`Missing component` error with pods + component placed on route folder

### ISSUE THREAD

**Issue by miguelcobain** [embroider-build/embroider#1326]
So, I'm trying to migrate an existing app that uses pods to embroider and using `staticComponents: true`. 
The problem I'm having is that embroider complains that it can't find the component. This component was defined **inside a route folder*, not in `pods/components`.
This is a pattern that I personally really like. When I need a component just for a certain route, I create a component inside the same route folder.
Apparently, embroider seems to ignore such components. 

My question twofold: 
- Is this a bug or am I just using a feature that was never intended to be used?
- What would be the appropriate migration path for this case?

**Comment by miguelcobain** [comment]
@void-mAlex I don't think I explained myself correctly, but my components are indeed inside `app/pods`.

The thing is that they're not as, for example, `app/pods/components/my-component/template.hbs`, but rather as `app/pods/some-route/my-component/template.hbs`.

So, the condition of being inside `app/pods`, is fulfilled.

**Comment by void-mAlex** [comment]
yes the expectation from pods are that components are still within the `app/pods/components` folder and the rest are routes
unless I'm mistaken there you've declared a sub-route called `my-component` which is why it's not working

**Comment by ef4** [comment]
I'm open to supporting more of the old pods use cases if people want to send PRs, but it's not something I am actively spending my effort on. You can see our pod resolution support here: 

https://github.com/embroider-build/embroider/blob/21eae416d9fa85ea6f9be55945c44ab3da2c655b/packages/core/src/module-resolver.ts#L353-L371

> What would be the appropriate migration path for this case?

Adopt Ember's [first-class component templates](https://github.com/emberjs/rfcs/blob/master/text/0779-first-class-component-templates.md) and then you can organize your components however you like, since they're normal Javascript imports. This is fully-working on stable ember versions right now with the ember-template-imports addon. It will move to "recommended" once all the docs and blueprints are updated to match.

**Comment by miguelcobain** [comment]
@ef4 thanks for that helpful pointer!
I think supporting these edge cases help people use embroider sooner. I'm totally willing to give it a try.

I just have a question: the js case I think is relatively trivial because the `suffix` is still `component`. So the change would be:
```diff
if (pods) { 
-   yield { prefix: `${pods}/components/`, suffix: '/component' };
+   yield { prefix: `${pods}/`, suffix: '/component' }; 
}
```
And I believe this would catch any component inside the pods directory, as I think is the case with classic pods.

However, the case for template-only components might not be so easy. If we do:
```diff
if (pods) {
-   yield { prefix: `${pods}/components/`, suffix: '/template' }; 
+   yield { prefix: `${pods}/`, suffix: '/template' }; 
}
```
would this also catch the regular route templates, because their filename is also `template.hbs`?
Or would it still work fine because this resolution is only "tried" if there is some attempt to invoke that component?

**Comment by void-mAlex** [comment]
@miguelcobain my question then would be how you can tell a route template.hbs apart from a component one?

**Comment by miguelcobain** [comment]
@void-mAlex yes. That was basically my question on my comment above.

I *think* it might not be a problem, because the resolution might only kick in if you write something like `<MyRoute::MyComponent />`.
In other words, you don't need to tell them apart because you explicitly invoke the components you want.

**Comment by miguelcobain** [comment]
The only valid sub-routes are determined by `router.js`, not by the filesystem, AFAIK. So, no problem in having arbitrary directories inside a route folder, as long as the names don't clash with sub-routes defined in `router.js`.

**Comment by ef4** [comment]
> The only valid sub-routes are determined by router.js, not by the filesystem, AFAIK. So, no problem in having arbitrary directories inside a route folder, as long as the names don't clash with sub-routes defined in router.js.

Yeah, but it is a problem for embroider because the router map is not, in general, statically analyzable. We don't know at build time what it says, because it can invoke arbitrary code that only works in the browser. But we do need to know at build time which templates are routes vs components in order to make features like `staticComponents` and `splitAtRoutes` work.

The first-class components feature happens to address this problem as well, since those components end in `.gjs` and not `.hbs`, so they can't be confused with a route template. However, that is not really the full story because we're going to want `.gjs` route templates too, it's just that we don't have that design finalized yet. Your case is a good input to that design. Next generation router should have some way of making it statically clear which is which.
