### ISSUE TITLE
Could not find module `ember-power-calendar-utils`

### ISSUE THREAD

**Issue by josemarluedke** [embroider-build/embroider#134]
Now that I have been unblocked by my previous issue, I got a new one.

This is related to ember-power-calendar, as it is doing some dynamic package under the hood. This works in classic Ember CLI, so that's why I'm opening it here. Pinging @cibernox to be in the loop here as well.

**The error:**

It only appears in the browser, not in the terminal as similar errors.

```
loader.js:247 Uncaught Error: Could not find module `ember-power-calendar-utils` imported from `(require)`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at requireModule (loader.js:24)
    at w._embroider_ (my-embroider-test.js:10)
    at eval (webpack:///external_%22_embroider_(:4200/\%22ember-power-calendar-utils\%22)%22?:1:18)
    at Object.ember-power-calendar-utils (chunk.8f1de7ceb06e8364c248.js:164)
    at __webpack_require__ (chunk.8f1de7ceb06e8364c248.js:79)
    at eval (power-calendar.js:4)
    at Module../node_modules/ember-power-calendar/components/power-calendar.js (chunk.5f9c7a14021a58709b9c.js:1695)
    at __webpack_require__ (chunk.8f1de7ceb06e8364c248.js:79)
```

**Embroider Version:**
v0.3.4

**Reproduction:**
https://github.com/josemarluedke/my-embroider-test/tree/power-calendar

**Comment by cibernox** [comment]
To clarify what weird thing I'm doing.

In ember-power-calendar I need to do date manipulation. Doing date manipulation without any date library is the shortest way to quit programming and become a farmer that there is, so I need to use one.

My favourite date libraries are moment.js and luxon.js, the latter being nicer than the former and lighter. I could have chosen one, say, luxon.js, but that'd mean I have to ship a heavy library to an app that might already be using moment.js.

What I did is create a handful of library-agnostic date helpers, and implement them in them using both libraries in `ember-power-calendar-moment` and `ember-power-calendar-luxon`. In both I do a little bit of [broccoli trickery](https://github.com/cibernox/ember-power-calendar-luxon/blob/master/index.js#L11-L22) to make them export those helpers in the same import path, so the users gets to choose what date-library is their favorite based without bloat the size of the app.

If there is a way of refactoring this to make it easier for embroider to digest I'm all ears.

**Comment by ef4** [comment]
I feel like I should start handing out awards to clever addon authors for discovering new ways to escape their package's own namespace. 😛 This is the fourth method identified so far.

PR #136 fixes this case by applying capabilities we were already using for the `addonTestSupport` trees to also monitor and fix `addon` trees. With that PR I was able to make ember-power-calendar work correctly in a sample app.

It's not quite enough to make ember-power-calendar's own test suite work under embroider, because (1) there's some unrelated broken stuff around the legacy-demo route, which imports things that don't really work anymore as far as I can tell, (2) the test suite does `require('moment')` rather than `import "moment"`, and that evades Embroider's namespace rewriting system. 

The answer for how to avoid all this dynamism is to use the [@embroider/macros]. This is a good demonstration use case, so I will try to make a PR to ember-power-calendar showing how it would work.
