### ISSUE TITLE
Error: Could not find module `sockette` imported from `(require)`

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#139]
Reproduction: 
- clone https://github.com/Turbo87/ogn-web-viewer/tree/embroider
- `ember s`

`sockette` is being imported in the `ws` service and it is also included as a module in one of the generated chunks. Unfortunately, it is being included in the third chunk and the second chunk is trying to import it, so it breaks.

**Comment by Turbo87** [comment]
one additional data point: this works fine as long as I also use `ember-auto-import`, but as soon as I only use embroider to handle the npm imports it fails

**Comment by ef4** [comment]
Ah yes, so this is intentional but confusing. The issue is that our out-of-the-box behavior is to faithfully keep the existing semantics of Ember apps. In normal ember apps, it would be a breaking change to suddenly start making things like `import "qunit"` resolve directly to packages in node_modules, rather than use their current runtime meanings.

We can make it opt-in for apps to get this behavior, but I think there's more to it than just adding an  option that enables imports. We should really codify what it means to author an *app* natively "in v2 format".  That is a momentous step, because once you step over that line you stop being buildable via normal ember-cli. 

But for now, keeping ember-auto-import gives exactly the right behavior. We treat it solely as a declaration that you expect imports from NPM to work. ember-auto-import doesn't actually run at all, it automatically gets disabled in favor of embroider.

Up until now, we haven't added any features that don't work safely in regular ember-cli builds. (That is, you might lose some optimizations like tree shaking and splitting, but correctness is maintained.) That is why ember-auto-import is the safest way to enable imports -- it means your imports keep working in both kinds of builds.

**Comment by tomwayson** [comment]
I think you should definitely add something about this to the README. It was my expectation that ember-auto-import would not be needed w/ embroider in order to automagically `import` from node_modules.

**Comment by NullVoxPopuli** [comment]
Looks like this may be resolved -- if anyone has further questions, please feel free to open a new issue! :partying_face:
