### ISSUE TITLE
Differences in behavior with template transforms

### ISSUE THREAD

**Issue by dfreeman** [embroider-build/embroider#141]
I realize template transforms aren't really public API, and also that the changes I'm seeing here may be intentional, but I wanted to bring them up just to get clarity. I'm noticing two specific differences in how template transforms get invoked:
 - the `moduleName` they receive is now the absolute path on disk of the input file rather than the template's 'logical' path in the application
 - transforms are being invoked for templates coming from addons, rather than just the app

I wrote a [simple demo in freshly-generated app](https://github.com/dfreeman/template-transform-with-embroider/commit/51ab11d492ce410db92a757625a6dc5bafec7116) that registers a transform that just logs the module name of the files it's invoked on.

With the classic build pipeline, I see:
```
embroider-app/templates/application.hbs
```

With Embroider's `compatBuild`, I see:
```
/private/var/folders/5m/q_433rys3rjb60zs14zd88nc0000gn/T/embroider/40f1b5/templates/application.hbs
/private/var/folders/5m/q_433rys3rjb60zs14zd88nc0000gn/T/embroider/40f1b5/node_modules/ember-welcome-page/templates/components/welcome-page.hbs
/private/var/folders/5m/q_433rys3rjb60zs14zd88nc0000gn/T/embroider/40f1b5/node_modules/@ember/test-helpers/setup-rendering-context.js
/private/var/folders/5m/q_433rys3rjb60zs14zd88nc0000gn/T/embroider/40f1b5/node_modules/@ember/test-helpers/setup-rendering-context.js
```

**Comment by ef4** [comment]
Yes, this is intentional, although we could invest a bit of effort to give existing AST transforms a more faithful reproduction of the old semantics if that turns out to be important.

The issue comes down to whether we handle the app's own custom AST transforms (and babel plugins, which are in exactly the same boat) in stage1 or stage3.

Transforms that run in stage3 definitely need to have a complete global view of the entire application, so having absolute paths to the files is critical. Likewise, processing the whole application (across package boundaries, app and addon code all together) is critical.

Whereas in stage1 we are doing a thing much closer to the traditional build, where we compile each package separately.

For addons, we already do the stricter thing, because we must. We run custom transforms against each package one-by-one. The reason we must is that we don't want to have a multitude of different configurations later in stage3, so we need to normalize to one lingua franca.

But for the app, we are currently more lax. There's not a pressing reason to compile away the custom features in stage1, because there is no problem of multiple configurations. The app's customized language can simply dominate and apply to the entire final stage3 build.

As long as everybody's transforms (babel and template) are **additive** to the base language this should be entirely safe. That is the theory I've been operating under.

**Comment by ef4** [comment]
After re-evaluating I think we can make this problem go away.

When https://github.com/embroider-build/embroider/pull/243 lands it will fix this issue, and AST transforms will see the traditional `moduleName`, the same as they see under classic ember-cli.

The few transforms that need the full path (which is right now just embroider's own) can use a new property we pass through named `filename`.

**Comment by ef4** [comment]
(Sorry if you already did hacks in your addons to work around this.)

**Comment by dfreeman** [comment]
Fortunately this was an instance where I was procrastinating on solving the problem and it actually paid off 🙃

Thanks for landing #243! Do you have any sense of when the next embroider release will happen?
