### ISSUE TITLE
Duplicate lazy loading 

### ISSUE THREAD

**Issue by villander** [embroider-build/embroider#144]
@ef4 I see that if I use `x-modal` component for example in two routes `route-one` and `route-two` and both are lazy-loading the `splitAtRoutes` will load two times the same component, doing a duplicated work needless. Is this that happens?

**Comment by ef4** [comment]
Embroider itself is not directly responsible for chunk optimization decisions like that. We delegate to a stage3 packager, which right now is Webpack. So this is mostly a question about what Webpack does.

But the answer is: it depends. Sometimes having the same module in multiple chunks is the optimal choice. There is a tradeoff between keeping the amount of code transferred as small as possible and keeping the number of network requests reasonable.

Remember that users can move through the app is many possible orders. Each lazy route they visit brings additional modules into the app. Some users who encounter `route-two` will already have `x-modal` (because they visited `route-one` earlier). But other users who encounter `route-two` will *not* already have `x-modal`, and will need to load it.

Webpack's solution to this problem is the splitChunksPlugin. It discovers modules that are needed by more than one chunk, and splits them out into a new chunk *if* it seems worth the additional network request. The exact parameters are tunable, but in development mode webpack won't bother splitting out the shared code unless it can find more than 10kB worth of shared code to put into the new chunk. Production builds have different default parameters.

**Comment by villander** [comment]
thank you very much for you explanation @ef4 makes all sense. It's always will depend of your product/users.
