### ISSUE TITLE
Instructions on how to use this on an app

### ISSUE THREAD

**Issue by shankarsridhar** [embroider-build/embroider#15]
First of all, thanks a lot for taking this effort. I would like to try this on my own ember app, but I can't seem to find any instructions on how to use this to build my ember app? 

Do I use this like an addon, is this available as part of an ember-cli unstable build? may be a link to some sample repo using this would be nice.

**Comment by villander** [comment]
@ef4 this [notes on travis-web](https://github.com/ef4/travis-web/blob/embroider/EMBROIDER.md) are up-to-date?

**Comment by villander** [comment]
@ef4 I'm using this notes - https://github.com/embroider-build/embroider#how-to-try-it

and your branch [ember-update](https://github.com/ef4/travis-web/commits/embroider-update) on travis fork, but I have this error when run `ember s`:

```
Build Error (PackagerRunner)

webpack returned errors to @embroider/webpack


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.e0cceb6695da5736b5a7d528e086ff80.log
```

**Comment by ef4** [comment]
The [README](https://github.com/embroider-build/embroider#how-to-try-it) is now the best source of instructions for how to try it. A lot has been simplified since those other instructions.

 - no ember-cli fork is needed
 - there's a prepackaged default build pipeline so there's less to put into your own ember-cli-build.js

There are still open issues that I expect many apps would hit, but I expect it to work completely in a newly generated ember app.

**Comment by villander** [comment]
@ ef4 but how can we see the bundles after the installation and execution of embroider? Where do they stay? how can I put one of them to load on demand?
