### ISSUE TITLE
Embroider optimized fails with Ember Data 4.12.x

### ISSUE THREAD

**Issue by jrjohnson** [embroider-build/embroider#1506]
In an addon with ember-data installed the [embroider optimized scenario](https://github.com/ilios/common/actions/runs/5426907988/jobs/9869666714) fails with:

```
Uncaught Error: Could not find module `@ember-data/store` imported from `(require)
```

Steps to reproduce

1. `$ ember addon emberFiveDataFourEmbroider`
2. `$ ember install ember-data@4.12.3`
3. `$ ember try:one embroider-optimized`

Just in case I tried it after the release of `v3.1.4` and it still fails. It passes with ember-data v5.x (or least doesn't fail in this obvious way).

**Comment by Windvis** [comment]
It seems the compat adapters are [disabled on ember-data 4.11.1+](https://github.com/embroider-build/embroider/blob/63f68367fcffecc372360adff7172dfb71416fca/packages/compat/src/compat-adapters/ember-data.ts#L20). It looks like v4.* isn't Embroider compatible and the adapters only hid the underlying issue?

`@ember-data/debug` is still importing from `@ember-data/store` without listing it as a dependency: https://github.com/emberjs/data/blob/00e572aa2d4315fda5aeba03540e9d81be6297bb/packages/debug/addon/setup.js#L3

In v5 that file is removed so that could explain why it works there.

So I think enabling (some of) the compat adapters might be a workaround if this can't be easily fixed on the Ember Data side.

**Comment by Windvis** [comment]
Small update: `@ember-data/debug` 4.12.3 now lists `@ember-data/store` as a [peerDependency](https://github.com/emberjs/data/blob/900ce877f041d2c2736ce33716582f95f56bd936/packages/debug/package.json#L19), but I still see the same runtime error after updating. So something else might still be going on. (I deleted the `node_modules/.embroider` folder to be sure).

**Comment by jrjohnson** [comment]
Confirmed as still failing with ember-data `v4.12.3` as well as `v3.2.0` of embroider libs with the same error message: 
`not ok 1 Chrome 114.0 - [undefined ms] - Global error: Uncaught Error: Could not find module `@ember-data/store` imported from `(require)` at http://localhost:7357/assets/vendor.js, line 254`

I also touched up the issue name and the reproduction steps.

**Comment by mkszepp** [comment]
There was forgot to disable the compact adapter for `@ember-data/debug` (https://github.com/embroider-build/embroider/blob/63f68367fcffecc372360adff7172dfb71416fca/packages/compat/src/compat-adapters/%40ember-data/debug.ts) 

Workaround is to disable the `compactAdapter` in app:
```
return require('@embroider/compat').compatBuild(app, Webpack, {
    skipBabel: [
      {
        package: 'qunit',
      },
    ],
    staticAddonTestSupportTrees: true,
    staticAddonTrees: true,
    staticHelpers: true,
    staticComponents: true,
    compatAdapters: new Map([
      ['@ember-data/debug', null],
    ]),
  });
```
