### ISSUE TITLE
Route splitting on pods found under `./app/routes/`

### ISSUE THREAD

**Issue by evoactivity** [embroider-build/embroider#1533]
Repro repo: https://github.com/evoactivity/embroider-route-split-pods-routes-dir

When pods are found in the `./app/routes/` directory by setting `podModulePrefix` to `my-app/routes` _and_ they are route split the routes do not load with no runtime or build errors.

**Comment by ef4** [comment]
I think all that is needed to fix this case is re-ordering the calls to the classic and pods implementations here:

https://github.com/embroider-build/embroider/blob/9834d5b0a6668d0934ff25af0ed1b79f3b2ec2e9/packages/core/src/app-files.ts#L111-L112

Settings podsModulePrefix to `my-app/routes` means that your route files also match the classic route files handling, and since that gets tried first it doesn't ever try to do the pod-specific handling.

**Comment by evoactivity** [comment]
I tried a quick patch to app-files.js in my node_modules to confirm and it does indeed fix this case.
