### ISSUE TITLE
I had an idea aroun how eventual Vite usage could look

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#1539]
Just had an idea and wanted to write it down -- feedback welcome,

_when we eventually can use a vite config, instead of broccoli for starting ember_
I was thinking it could maybe look something like this
```ts
// vite.config.ts
import { defineConfig } from 'vite';
import { ember, emberTesting } from '@embroider/vite';
import { emberData } from '@ember-data/vite';

export default defineConfig({
  plugins: [
    // does all the service / route / helper registration stuff, 
    // does all the compatibility stuff, maybe unless strict: true?
    // maybe has all the same options as embroider/compat?
    ember({ strict: true }),
    // sets up the infra for qunit, and which path to place it on?
    // this way, if folks need '/tests' for their users, they could 
    // rename the tests route to something else
    // obvs this would disable itself in production builds unless configured otherwise
    emberTesting('/tests'),
    // ember-data has some build-time config to emit cc @runspired
    emberData(),
  ]
});
```

## Open questions / thoughts

The main thing I don't have figured it out is how to control testing via the CLI.
Today we have `testem`. but it is [impossible](https://github.com/NullVoxPopuli/a-proper-test-launcher/pull/2) to use `testem` with vite hosting qunit tests without re-writing good chunks of testem (testem is a decade behind on maintenance, and still assumes promises might not exist).
The qunit-in-vite part [is pretty easy](https://github.com/NullVoxPopuli/a-proper-test-launcher), and with import.meta.glob, getting vite to import all the tests is super straight-forward. 

There is this project, which seems interesting: https://github.com/izelnakri/qunitx-cli
I [haven't been able to get it working yet](https://github.com/izelnakri/qunitx/issues/74), but if it can replace testem, and support regular qunit, I think it could be a viable option.
cc @izelnakri :wave: 

I've looked into vitest's browser support, and they don't want to expose the utils for us to hook up our own test framework (or for anyone to do so) -- they want want folks using their own test framework built in to vitest.. which.. is fair.

Playwright does not provide a way to integrate other test-frameworks, and instead wants tests to be on the node side, driving the browser, rather than having the tests _in_ the browser (like qunit, mocha, jasmine, etc etc)
`@web/test-runner` does not provide a way to hook in to an existing vite server / external page hosting tests, and wants to also control the build, and also wants custom browser installations..
Puppeteer has poor ergonomics and requires custom browser installations..

The main thing with a test launcher is that
- we want to use the browsers already installed on the system (this is what has made testem actually really good, usability-wise), and not have `postinstall` scripts (big security risk) that require us to download _drivers_ for browsers -- or in some cases, download whole browsers through those `postinstall` scripts (puppeteer and webdriver are known for doing this)

**Comment by ef4** [comment]
I already have stock ember tests working interactively in the browser with vite (the `ember s` case, not the `ember test` case). That case is pretty simple since it's really just a different kind of entrypoint to the app. To see it:

1. clone the `vite-app` branch of embroider.
2. cd `tests/vite-app`
3. `pnpm start`
4. visit http://localhost:5137/tests/ (note the trailing slash!)

For CI, `vite build` followed by `ember test --path ./to/the/dist` probably just works. Arguably it's more correct to run CI tests that way anyway, compared with `vite dev`, because it tests the full rollup build which is closer to what you'll use in production. (This case doesn't work on the branch at the moment because I don't have public asset handling configured in the production build. )

The only place where we'll really *need* tests running against `vite dev` is in embroider's own tests, to ensure that we've got `vite dev` working right.

I'm not against people exploring and proposing alternative test frameworks, it's just not really a blocker to adopting vite and I'd rather solve one problem at a time. I have heard multiple folks saying they think we're very tightly tied to qunit, but it's just not true. The infra in this area is actually pretty well done and pluggable. Making `@ember/test-helpers` work in an alternative environment for example is straightforward because it was designed for that.

**Comment by ef4** [comment]
I'm closing this because it's not an issue. Also I think the speculative vite config is likely to confuse more than it illuminates.

**Comment by NullVoxPopuli** [comment]
> I have heard multiple folks saying they think we're very tightly tied to qunit, but it's just not true

yes, I did not mean imply on perpetuate the assumption of being tightly coupled to qunit!!

having worked with ember-qunit a bunch in prep for the ember-qunit@v8 / v2-addon release, I'm fairly confident I can develop adapters for other test frameworks quite easily.

however, I was working under the assumption that we wanted exact parity with the way folks run tests today -- which.. idk why I assumed that... but here we are!
I'm glad we have some flexibility here though -- there are a number of folks at AuditBoard as well that prefer separating out the build + test processes, so they'll be happy that that may/will become the preferred approach!
