### ISSUE TITLE
Should `loader.js` be marked as external and indirected to the global?

### ISSUE THREAD

**Issue by chancancode** [embroider-build/embroider#1545]
i.e. should this work out of the box?

```js
import { define, require } from "loader.js";

if (!require.has("foo")) {
  define("foo", function() { /* ... */ });
}
```

While we don't necessarily encourage people to use the runtime loader, it's a thing and it's sometimes necessary for compat hacks. And it is similar to `@glimmer/validator` in that there really can only be one copy, so it seems reasonable to give it the same treatment.

The alternative is doing something like `globalThis.define(...)` which seems worse because that's less statically analyzable, harder to detect/deprecate/etc. It also gives us more options to migrate away, rename the global, etc, down the road.

FWIW, it currently this fails with:

```
Module not found: Error: Can't resolve '.' in '/private/tmp/zomg/node_modules/.embroider/rewritten-packages/loader.js.b05f7bb0'
```

**Comment by ef4** [comment]
I don't think this is a good idea. It would require new special-case handling in several different packages and the migrations would be error prone. You'd need to special-case it in ember-auto-import, `@embroider/shared-internals`, and ember-cli, and deal with mixed-versions between each of those.

Since loader.js exists only for compatibility, I think we should touch it as little as possible.

> which seems worse because that's less statically analyzable, harder to detect/deprecate/etc. 

I disagree with the assumption that the import is easier for us to deal with. ES-module aware systems will happily ignore `globalThis.define()` but as soon as you start writing them as imports and thus pretending they interoperate with ES modules, you start to incur extra compatibility costs. For example, just today I had to add special handling to try to make vite's pre-analysis not die on `import require from "require"`. Had the author of that code just used globalThis it would all have worked seamlessly.

**Comment by chancancode** [comment]
Discussed this with @ef4 in person, but posting it here for context/history

Mostly I just want to know what is the "sanctioned" way to interact with the runtime loader reliably (so you don't run into issues like #1546). I didn't realize `import require from "require";` is considered a bad pattern so that's good to know. I would actually be fine with `globalThis.define` as the "correct" way to do it.

That said, I did wanted to explore this a little further: the thought process is that `loader.js` itself is already _real_ package (unlike `import require from "require";`), and as far as I can tell, it's already quite well-behaved commonjs package, and `define`/`require` are _real_ cjs named exports from the entry point specified in `package.json`, so it feels like importing it should just work, and if it doesn't, then maybe our compat shim is breaking something.

So I made this vanilla webpack project: https://github.com/chancancode/loaderjs-webpack

Things _did_ almost work with the exception that:

1. loader.js doesn't attach it to globalThis: part of the problem is `this` is not what it expected, but also I actually just didn't find the code where it _actually_ does that from reading the source, but anyway it's easy enough to attach it manually
2. **However** the more important thing is that, unfortunately, `require()` is basically treated as an un-shadowable keyword in webpack. In [bar.js](https://github.com/chancancode/loaderjs-webpack/blob/main/src/bar.js), if you stop renaming the `require` import, the build immediately breaks because webpack intercepted the `require` as commonjs require to find the "foo" module, and fails, instead of letting the imported require shadows. (Which is what @ef4 hinted at in #1546 as well)

Personally I feel like this is a webpack bug (at least it should have errored specifically at the point of shadowing), but it is what it is.

**Comment by chancancode** [comment]
I think there is probably still some value in ensure we don't "break" this more than webpack does (compared to the example project I have in here), but it's not very high value and fixing it the "proper way" the way I thought (by making our compat stuff do less) does have risk of breaking things. Someone else could probably pick this up if they care enough and ensure no breakages, but I'm closing this for now.

**Comment by ef4** [comment]
> Personally I feel like this is a webpack bug (at least it should have errored specifically at the point of shadowing), but it is what it is.

Oh yes indeed, and [I filed that bug](https://github.com/webpack/webpack/issues/12154) a long time ago, and didn't really get satisfaction. We're using javascript/auto mode here, and it definitely gets the scoping wrong. 

Their response that "yeah, well, auto mode is a hack that we want to get rid up" isn't wrong, but clearly it's still not gone. I will also point out that so long as you want `importSync` to maintain its timing we *need* auto-mode, because we compile `importSync` to a `require` that webpack handles as CJS.
