### ISSUE TITLE
addon-dev (v4) addon.publicAssets adds path to map values

### ISSUE THREAD

**Issue by basz** [embroider-build/embroider#1569]
The ability to write keep the metadata public-assets in sync with files inside public is new in addon-dev v4

https://github.com/embroider-build/embroider/blob/main/packages/addon-dev/src/rollup-public-assets.ts

I've noticed that it adds the path as a directory in the value of the map.

Intend; Add all files inside 'public-assets' to the map.

given a directory with an asset

```
/public-assets/icons/folder-x.svg`
```
and a config of;
```
addon.publicAssets('public-assets'),
```
results in; 
```
"./public-assets/icons/folder-x.svg": "/@shoelace-style/ember/public-assets/icons/folder-x.svg",
```      

where '/@shoelace-style/ember' is the addon name. good!

'public-assets' is undesired

I would expect all assets to go to a directory "addon-name" => '/@shoelace-style/ember/icons/folder-x.svg'

**Comment by NullVoxPopuli** [comment]
in the modern ESM world, there isn't a concept of "public tree merging".

you'll want to import assets, and webpack/vite/etc will "do the right thing", depending on which plugin you choose.
That could be
- give you an URL to the asset
- give you the actual SVG itself for you to place in the DOM
- etc

**Comment by basz** [comment]
yes i've been reading comments here along that line. Deemed discouraged but sometimes a useful feature.

I will say that even though modern ESM might as it should work I noticed that in v2 addons it doesn't work (yet) out of the box for assets and these concepts are pretty difficult to grasp. I would really want a directory I can dump stuff in to be publicly available in my app/addon.

**Comment by ef4** [comment]
@NullVoxPopuli that's missing the point of the public-assets feature.

The public-assets feature is still important for assets that are actually **public**.  If an asset is entirely internal to your addon, sure, we think you'll want to use asset importing (although @basz is correct that we don't have an RFC standardizing that automatically for all addons yet). But some assets are not internal. Their public URL is part of what you're offering to the web. 

So it's actually pretty critical that this feature allows addons to put assets into *any* public URL. That's why we don't enforce namespacing by addon name in the output.

Looking at the implementation, I agree that what's currently in addon-dev is not really correct. A clearer API would use names to make it clear that you have control over both the internal and external paths:

```js
// put things from ./my-public-assets-dir into the root of the app
publicAssets({ from: "./my-public-assets-dir", toPublicPath: "/" })

// put things from ./my-fonts into /my-addon-name
publicAssets({ from: "./my-fonts", toPublicPath: "/my-addon-name", include: ["*.ttf"] })
```

**Comment by basz** [comment]
To keep compatibility with current v4. We could keep the current interface (path, opts) and add a toPublicPath property to opts. And when omitted it keeps current behavior? 

Even if the extra path segment is bug imo.

Dunno if bc is important here?

**Comment by Windvis** [comment]
@ef4 Some questions about the suggested API:

- Do we still want to support the "old" API and / or deprecate it?
- What should the default behavior be if `toPublicPath` isn't configured? Do we throw an error? Do we default to the addon name? addon name + `from' value (which is the current behaviour)? The root of the public folder? Something else?
- Any suggestions on how to add tests for this. How extensive does it need to be tested? Trying to fit multiple variations in existing scenario tests might be tricky (but I'm not super familiar with the testing setup so I could be wrong). Adding a testing setup to the addon-dev package could work but that would probably also require some sort of fixture setup?

For those running into this you can work around the problem by:
- adding a custom rollup plugin that does the thing you want (copy the code from the bundled one and modify it).
- using the current plugin once so it modifies the package.json and removing it again. Modify the paths manually afterwards. (New assets then need to be added by hand which is not ideal if assets are regularly changed)

**Comment by ef4** [comment]
> Do we still want to support the "old" API or deprecate it?

Deprecate or remove it, whatever is easy. Breaking changes in `@embroider/addon-dev` are not as big a deal as in many of our other packages, because it doesn't have ecosystem-wide effects. There's no pressure from your consuming apps to use any particular version of addon-dev.

> What should the default behavior be if toPublicPath isn't configured? 

I'm fine with throwing an error, especially if the error tells you exactly what to type instead.

> Any suggestions on how to add tests for this. 

I think it's enough to have one example usage within in v2-addon-dev-test.ts or v2-addon-dev-watch-test.ts.

**Comment by simonihmig** [comment]
> where '/@shoelace-style/ember' is the addon name. good! 'public-assets' is undesired

This has been addressed in https://github.com/embroider-build/embroider/pull/2082 (will be in next major).

> So it's actually pretty critical that this feature allows addons to put assets into any public URL. That's why we don't enforce namespacing by addon name in the output.

I think this is already given with the `namespace` option (see [here](https://github.com/embroider-build/embroider/blob/main/packages/addon-dev/src/rollup-public-assets.ts#L54)), which you could set to an empty string, which would allow you to have public assets without any namespacing (e.g. `/robots.txt`). 

I think we have addressed the concerns here, right? Closing this, feel free to reopen should you disagree! :)
