### ISSUE TITLE
Feature request: allow setting webpack's __webpack_public_path__

### ISSUE THREAD

**Issue by raycohen** [embroider-build/embroider#1796]
Webpack has [a feature](https://webpack.js.org/guides/public-path/#on-the-fly) that allows deciding at runtime what host to use for loading build files.

The API to do it is a bit odd and requires setting a seemingly magic variable (`__webpack_public_path__`) at the very beginning of your entry point file. Since embroider controls the entry point file handed to webpack behind the scenes, there's currently no way to accomplish this.

In practice, this feature allows you to do something like

```
__webpack_public_path__ = document.querySelector('meta[name="cdnHostName"]').content;
```

and now your server can control what CDN is used at runtime by including that meta tag in the html.

In my case I am uploading the same build assets to multiple CDNs and would like the ability to dynamically decide between them. My ember build takes ~30 minutes in CI so running the build multiple times just to be able to switch CDN is not feasible for me.

**Comment by ef4** [comment]
This doesn't require any special support in embroider. You can set `__webpack_public_path__` anywhere reasonably early in the app and it will work.

It's important to note what `__webpack_public_path__` can and cannot do. It controls the loading of lazy chunks. So it affects how `import()` will get implemented. But it cannot control the loading of initial chunks, since webpack's own runtime code that reads `__webpack_public_path__` is *inside* those initial chunks.

**Comment by ef4** [comment]
If you want to be really sure you can put your own inline script tag first in the HTML.

```html
<script>
  __webpack_public_path__ = document.querySelector('meta[name="cdnHostName"]').content;
</script>
```

Though in practice it would be very surprising to me if any Ember app is actually trying to dynamic import things before, say, `app.js` has evaluated, so doing it in app.js is likely to be fine.
