### ISSUE TITLE
FastBoot + Embroider + browser-only library issue

### ISSUE THREAD

**Issue by Windvis** [embroider-build/embroider#1809]
I recently tried to convert a FastBoot-ed app to Embroider but when I enabled the static flags the following error was thrown:

> TypeError: Ue.addHook is not a function

I was able to reproduce the problem in a [StackBlitz](https://stackblitz.com/edit/github-4u6v9p?file=app%2Ftemplates%2Fapplication.hbs).

The reproduction contains a custom modifier that imports and runs a [browser-only library](https://github.com/TriplyDB/Yasgui). The error message points to [this line in that library](https://github.com/TriplyDB/Yasgui/blob/e50ae2dd2f4d4873a5382edd44b7d2670418549a/packages/yasr/src/helpers/sanitize.ts#L2).

It seems that we were already using a FastBoot check, even in the classic build, which looks like this:

```hbs
{{#unless this.fastboot.isFastBoot}}
  <div {{yasgui}}></div>
{{/unless}}
```

Without that the error is also thrown in the classic build, so it's the import of the library that triggers it. 

When enabling Embroider I noticed that everything still worked under the "safe" preset, but once I enabled the static flags the error is thrown.

I'm not sure if this is a bug in Embroider. I was able to get it to work by lazy loading the modifier when not in FastBoot, but it's not the most elegant solution.

**Comment by ef4** [comment]
Hi @Windvis.

You will have the same problem even without embroider when you try to adopt template tag. In both cases it's because the natural way to import the `yasgui` modifier is as a regular static import, and that makes it's implementation (and it's implementation's dependencies) evaluate eagerly whether or not you invoke it.

You're correct that you can only avoid evaluating it by lazily loading it with `import()`. Top-level await makes this less awkward, since you can absorb the `await import` in more places. (Top-level await does not work everywhere under `@embroider/webpack` yet because it doesn't interoperate with Ember's AMD loader.)

Fastboot's build-in ability to overwrite files with fastboot-specific versions is supported in Embroider. That may be the least awkward solution right now. So you could have `app/modifiers/yasgui.js` with the real implementation and `fastboot/modifiers/yasgui.js` with a no-op implementation. That should do the right thing in both cases under embroider.

**Comment by Windvis** [comment]
Hi @ef4 

I wasn't aware of the file override ability of FastBoot. Using a no-op did indeed fix the problem. Thanks for the hint!

Closing this since it's not an Embroider bug 👍.
