### ISSUE TITLE
Can't resolve 'ember-cli-surge/blueprints/surge'

### ISSUE THREAD

**Issue by balinterdi** [embroider-build/embroider#259]
After having linked the latest embroider packages and trying to build/run the app, I get the following error:

> Module not found: Error: Can't resolve 'ember-cli-surge/blueprints/surge' in 
'/private/var/folders/qb/zkbx5mt13qggl5zc8h19fy4h0000gn/T/embroider/48c6b9/blueprints'

This is thrown [from this line](https://github.com/kiwiupover/ember-cli-surge/blob/master/app/blueprints/surge.js):

> export { default } from 'ember-cli-surge/blueprints/surge';

I'm not sure if this is the correct way to import the blueprint, since it's actually under 
`ember-cli-surge/blueprints/ember-cli-surge/index.js` (see [here](https://github.com/kiwiupover/ember-cli-surge/blob/master/blueprints/ember-cli-surge/index.js)), but the build is successful if built the "classic" way (without Embroider).

**Comment by lifeart** [comment]
looks like blueprints are not prebuilded for new addon version

**Comment by lifeart** [comment]
@balinterdi looks like exactly as you mentioned.

![image](https://user-images.githubusercontent.com/1360552/60270465-27970c80-98f9-11e9-9ebd-d463efe40489.png)

**Comment by balinterdi** [comment]
To me this would imply that blueprints would just work without any extra action when switching to use Embroider. Do you interpret it differently?

**Comment by ef4** [comment]
It's true that we don't support blueprints in v2 addons yet. But that shouldn't be relevant, because `ember generate` and `ember build` are completely disconnected from each other. Embroider only affects the build. Blueprints run un-affected by Embroider.

This is a bug in ember-cli-surge. It is importing its blueprint code (which should only ever run in Node) into the app's runtime (browser) code. Specifically, [this file](https://github.com/kiwiupover/ember-cli-surge/blob/e867e716a4e9749ffa2268d224795281671e483a/app/blueprints/surge.js) probably needs to get deleted.

Here is a workaround until upstream can be fixed:

```js
return require('@embroider/compat').compatBuild(app, Webpack, {
    compatAdapters: new Map([[
      'ember-cli-surge',
      class extends (require('@embroider/compat').V1Addon) {
        get packageMeta() {
          let meta = super.packageMeta;
          delete meta['app-js'];
          return meta;
        }
      }
    ]])
  });
```
