### ISSUE TITLE
Excess RewritePackageJson trees observed

### ISSUE THREAD

**Issue by stefanpenner** [embroider-build/embroider#291]
When building a large app, with many nested addons we have observed excess RewritePackageJSON tree's.

Observed in the wild, rather than 9,933 broccoli nodes, we see in excess of 87,000 nodes.

This appears to severely impact build performance.

I believe, the fix may be that `v2Trees` creation of it's new `RewritePackageJson` to go through `throughTreeCache` if possible.

It may also be the case, that the entire result of `v2Tree` should in some circumstances go through the cache as well.

**Comment by ef4** [comment]
*Sigh*. Yes, ember-cli's super-linear build costs as the number of addons grows strikes again. 

I know @stefanpenner knows this already, but for interested readers: ember-cli doesn't just build each addon, it builds each addon for each time that addon is consumed by another package (meaning the app or another addon). This causes build costs to grow super-linearly as you add more addons and they depend on each other. Embroider's compat layer faithfully reproduces this expensive behavior because it has to. Whereas our new V2-formatted addons skip all that and build costs grow linearly in the number of addons, rather than super-linearly.

I agree, we can run the whole `v2Tree` through `throughTreeCache`, making a new embroider-specific category for it that won't collide with any existing category.

This would be a good PR for you or someone on your team, because you should be able to see an immediate performance impact in that giant app.

**Comment by rwjblue** [comment]
>  ember-cli doesn't just build each addon, it builds each addon for each time that addon is consumed by another package (meaning the app or another addon). This causes build costs to grow super-linearly as you add more addons and they depend on each other. 

This isn't quite correct, ember-cli will reuse the same addon tree based on the result of `cacheKeyForTree`. If the `cacheKeyForTree` is "stable" we will not create a new tree (e.g. we do not call `treeForAddon` again) and instead we will use the the cached tree.

**Comment by ef4** [comment]
Right, cacheKeyForTree is the bandaid on this more fundamental problem.

**Comment by stefanpenner** [comment]
> This would be a good PR for you or someone on your team, because you should be able to see an immediate performance impact in that giant app.

Ya. I wanted to make sure this approach sounded reasonable.

**Comment by stefanpenner** [comment]
I also changed the algorithm in broccoli, so it doesn't drop easy money on the table https://github.com/broccolijs/broccoli/pull/418

**Comment by tmquinn** [comment]
Starting on this...

**Comment by tmquinn** [comment]
@ef4 could you expand on 
>making a new embroider-specific category for it that won't collide with any existing category

I _think_ I've gotten familiar enough now to understand a response to this...

**Comment by ef4** [comment]
My comment was slightly misleading because I was misremember how the tree cache is currently implemented. 

All we really need to do is pick a new name to use as the second argument to `throughTreeCache` when we're caching the `v2Tree`. It's neither `"stock'` nor `"original"`, which are the existing categories that are used there.

**Comment by tmquinn** [comment]
So I've run into an issue.

My initial effort is to simply cache the RewritePackageJSON tree as such:
```js
  protected get v2Trees() {
    let { trees } = this.build();
    let packageJSONRewriter = this.throughTreeCache('addon', 'JSONRewriter', () => {
      return new RewritePackageJSON(this.rootTree, () => this.packageMeta);
    });
    if (packageJSONRewriter !== undefined) {
      trees.push(packageJSONRewriter);
    }
    return trees;
  }
```
The bulk of the tests pass, except when trying to build `test-packages/static-app`
I'm getting the error:
```
    Build Error (WaitForTrees)

    unable to locate component {{basic-dropdown/trigger}} referred to in rule {
      "dependsOnComponents": [
        "{{basic-dropdown/trigger}}",
        "{{basic-dropdown/content}}"
      ]
    }
```
So between the master build, and my caching build, the `components/basic-dropdown` is missing from the cached build... I'm trying to figure out how the cacheKeyFor tree gets utilized during the build, and I see it in ember-cli's treeFor in `addon.js` but execution never hits that path... is there any suggestion you'd have for looking in the right place to see why this is failing?

**Comment by tmquinn** [comment]
There are a number of things that I've done above that confuses me, going to shift to cacheing the v2Tree, which seems more inline with how I think the caching works

**Comment by acorncom** [comment]
Should this issue be closed at this point?

**Comment by ef4** [comment]
Yes, I think #305 fixed it.
