### ISSUE TITLE
Babel transpilation for npm dependencies

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#3]
https://github.com/embroider-build/embroider/blob/master/SPEC.md#own-javascript mentions that by default npm dependencies should not be transpiled. As I had already written in https://github.com/ef4/ember-auto-import/issues/41, I believe that we should apply ES latest to ES target by default for npm dependencies as many of them now target Node.js 8 or 10, which supports a lot ES features than some of the relevant browsers.

The spec mentions:
> Double transpilation is not safe in general, since choices get made about how to map between modules, AMD, UMD, etc.

I don't understand this part. I agree that double transpilation of module systems is a problem, but transpiling all other syntax to ES target syntax does not appear problematic to me. Am I missing something?

**Comment by ef4** [comment]
This would be relatively easy to enable, and I agree, it's probably correct. If you would like to try this out, it's a matter of changing `shouldTranspileFile` in `ember-webpack.ts`.

And you're right, we don't actually handle module-to-AMD in babel, so that was not relevant.

**Comment by ef4** [comment]
My latest thinking on this issue is https://github.com/ef4/ember-auto-import/issues/41#issuecomment-495717257

We should implement as described in that comment. We want embroider and ember-auto-import to work the same way, since auto-import is effectively a polyfill for embroider.

I think it's fine if the configuration option (`exclude`) lives under the same `ember-auto-import` even though embroider will also read it. In all existing apps and addons, the only way to get import-from-NPM behavior is to depend on ember-auto-import.

In native V2 packages, we can make a different rule, but that is not a thing yet.
