### ISSUE TITLE
How work code splitting/bundles here?

### ISSUE THREAD

**Issue by villander** [embroider-build/embroider#30]
@ef4 but how can we see the bundles after the installation and execution of embroider? Where do they stay? how can I put one of them to load on demand?

**Comment by ef4** [comment]
The set of bundles that gets output is deliberately opaque. That leaves us free to optimize it.

Apps should just express what they want in Javascript via `import` and `import()` and we will make sure that works at runtime.

(That said, while `import()` already works in embroider and always will, it's not something we want app developers to need to type very often. Because Ember's routing is entirely conventional, we should be able to automatically insert those dynamic imports per route, but that is not implemented here yet.)

**Comment by villander** [comment]
Sorry to go back on that. But I did not understand what we can dynamically load using `import()` in the embroider. Is this lazy loading or just code splitting?

Can I load on-demand components / services? I can do this via template too? if so, do you have an example?

I think there are missing examples of what can be separated as a bundle and how each of them is loaded dynamically.

about dynamic imports per route that would be wonderful, I'd love to be able to help with that.

**Comment by ef4** [comment]
> Is this lazy loading or just code splitting?

It's lazy, the point of dynamic `import()` is that you can do it whenever you're ready to load the code and not before.

> Can I load on-demand components/services or anything? I can do this via template too? if so, do you have an example?

No, not yet. I want to show some examples soon. Up until now I have been 100% focused on getting compatibility with existing apps, and haven't been focused on doing the new features & optimizations. I put those off because they're the easy part, but of course I realize people will want to see them to understand the point of the project. 😀

**Comment by villander** [comment]
makes all sense @ef4 

> Up until now I have been 100% focused on getting compatibility with existing apps, and haven't been focused on doing the new features & optimizations. I put those off because they're the easy part, but of course I realize people will want to see them to understand the point of the project.

such as code splitting and lazy loading is something the community is clamoring to see and as you said is the easy part, can we plan this with a roadmap, a new RFC or an attack plan for embroider? [because we know that we need something beyond the RFC's of packager and prebuilt addon](https://github.com/embroider-build/embroider/blob/master/SPEC.md#alternative-designs)

**Comment by ef4** [comment]
Code splitting is now implemented.
