### ISSUE TITLE
unit tests fail when splitAtRoutes is enabled

### ISSUE THREAD

**Issue by kandhavivekraj** [embroider-build/embroider#370]
Unit tests are failing for the routes that are split. 

It is possible to reproduce this by just running the unit tests with the filter option. I am guessing this is because since the routes are not visited, the chunks are not loaded.

**Comment by roomman** [comment]
Also experiencing this issue - unit tests fail for any Routes / Controllers included in Embroider's `splitAtRoutes` option, because `this.owner.lookup(...)` returns `undefined`.

**Comment by ef4** [comment]
Hmm, this is a good thing for us to document. These tests can't work the same way when you have route splitting.

*(I think it's a mistake that `ember generate route` gives you a unit test instead of an acceptance test by default. I think most people would be better served by acceptance tests, and those would work even with route splitting. But we should definitely explain what to do for unit tests too.)*

You can make them work manually by doing your own import and registration of the route:

```js
import { setupTest } from 'ember-qunit';
import { module, test } from 'qunit';
import SearchRoute from 'my-app/routes/search';

module('Unit | Route | search', function (hooks) {
  setupTest(hooks);

  hooks.beforeEach(function () {
    this.owner.register('route:subject', SearchRoute);
  });

  test('it works', function() {
    let route = this.owner.lookup('route:subject');
    ...
  });
});
```

**Comment by roomman** [comment]
Thanks so much @ef4, I really appreciate you taking time out to look at this and respond. 👍🏻

I can't understand how this hasn't been more of a topic of conversation on here. If Ember generated unit tests are fundamentally incompatible with code splitting, how has anyone with a CI setup got anything deployed?!

I definitely think there needs to be a note about this somewhere in the docs. I lost a good few days to this one, assuming that the error was related to some async behaviour in my app. Happy to offer up a PR that adds something to the README if that helps?

Thanks again 😀

**Comment by ef4** [comment]
Closing via https://github.com/embroider-build/embroider/commit/429589399c05b6d6f45566a36945428e0974d6c1
