### ISSUE TITLE
Causes issue with ember-inflector

### ISSUE THREAD

**Issue by makepanic** [embroider-build/embroider#382]
Hi,

I'm in the progress of investigating migrating to embroider again.
I found that configuring `ember-inflector` from an app causes external consumers to not get that configuration.

Example:

In an app, `initializers/inflector.ts` calls `inflector.uncountable(word)` to register the word as uncountable.
Now after using embroider, it seems like the inflector isntance, ember-data uses, is a different one.

I tried to overwrite the [`pathForType` method](https://github.com/emberjs/data/blob/85dbc55e7989157307ab897ac0b126bd777a724b/packages/adapter/addon/json-api.js#L229-L232), to use a locally imported ember-inflector and a call to `this._super`.

```
pathForType(modelName: string): string {
      let dasherized = dasherize(modelName);
      console.log(`pathForType: ${modelName}
local -> ${pluralize(dasherized)}
super -> ${this._super(modelName)}
`);
      return pluralize(dasherized);
    }
```

This causes the following log (modelName is `anon-signup` and configured as uncountable):

```
pathForType: anon-signup
local -> anon-signup
super -> anon-signups
```

I'm not sure if embroider is the place to fix this or somewhere else (probably not using an imported singleton).

**Comment by ef4** [comment]
Embroider gives each package (app or addon) exactly the dependencies it asks for. If it asks for its own copy of ember-inflector at a particular version, it will really get that copy. This is unlike ember-cli, which does a big merge of all different versions of the same dependency that are present.

In order to get the *same* copy of ember-inflector as the app, each addon needs to declare ember-inflector in `peerDependencies`, not `dependencies`. 

If they don't, you can workaround by using something like [Yarn selective dependency resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) to force the addon to share the same exact version that the app has.

**Comment by makepanic** [comment]
Thanks, it seems like using yarn resolutions solved the issue.
