### ISSUE TITLE
Rollup error from ember-data

### ISSUE THREAD

**Issue by villander** [embroider-build/embroider#40]
I'm using embroider 0.0.8 in my app. I have this error

```
➜  web_app git:(staging) ✗ ember s
Cannot stop: not the current node.
Build Error (OneShot)

Build Canceled: Broccoli Builder ran into an error with `Rollup` plugin. 💥
Could not resolve '../../../-debug' from tmp/rollup-cache_path-OzrZ2oRb.tmp/build/-private/system/references/belongs-to.js


Stack Trace and Error Report: /var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.f9e550f228f39a54667691efaab0d6b6.log
```

**Comment by ef4** [comment]
That looks like something in ember-data's own weird build is dying.

Please share the real error report (the contents of that mentioned file).

Also, I'm going to retitle this issue, it almost certainly has nothing to do with ember 3.8.

**Comment by villander** [comment]
@ef4 follow below the file `tmp/rollup-cache_path-mFGBieAk.tmp/build/-private/system/references/belongs-to.js`

```js
import { assertPolymorphicType } from "../../../-debug";
import Model from '../model/model';
import Reference from './reference';
import recordDataFor from '../record-data-for';
/**
 A BelongsToReference is a low-level API that allows users and
 addon author to perform meta-operations on a belongs-to
 relationship.

 @class BelongsToReference
 @namespace DS
 @extends DS.Reference
 */

export default class BelongsToReference extends Reference {
  constructor(store, parentInternalModel, belongsToRelationship, key) {
    super(store, parentInternalModel);
    this.key = key;
    this.belongsToRelationship = belongsToRelationship;
    this.type = belongsToRelationship.relationshipMeta.type;
    this.parent = parentInternalModel.recordReference;
    this.parentInternalModel = parentInternalModel; // TODO inverse
  }
  /**
   The `id` of the record that this reference refers to. Together, the
   `type()` and `id()` methods form a composite key for the identity
   map. This can be used to access the id of an async relationship
   without triggering a fetch that would normally happen if you
   attempted to use `record.get('relationship.id')`.
    Example
    ```javascript
   // models/blog.js
   export default DS.Model.extend({
      user: DS.belongsTo({ async: true })
    });
    let blog = store.push({
      data: {
        type: 'blog',
        id: 1,
        relationships: {
          user: {
            data: { type: 'user', id: 1 }
          }
        }
      }
    });
   let userRef = blog.belongsTo('user');
    // get the identifier of the reference
   if (userRef.remoteType() === "id") {
      let id = userRef.id();
    }
   ```
    @method id
   @return {String} The id of the record in this belongsTo relationship.
   */


  id() {
    var id = null;

    var resource = this._resource();

    if (resource && resource.data && resource.data.id) {
      id = resource.data.id;
    }

    return id;
  }

  _resource() {
    return this.recordData.getBelongsTo(this.key);
  }
  /**
   `push` can be used to update the data in the relationship and Ember
   Data will treat the new data as the conanical value of this
   relationship on the backend.
    Example
    ```javascript
   // models/blog.js
   export default DS.Model.extend({
      user: DS.belongsTo({ async: true })
    });
    let blog = store.push({
      data: {
        type: 'blog',
        id: 1,
        relationships: {
          user: {
            data: { type: 'user', id: 1 }
          }
        }
      }
    });
   let userRef = blog.belongsTo('user');
    // provide data for reference
   userRef.push({
      data: {
        type: 'user',
        id: 1,
        attributes: {
          username: "@user"
        }
      }
    }).then(function(user) {
      userRef.value() === user;
    });
   ```
    @method push
   @param {Object|Promise} objectOrPromise a promise that resolves to a JSONAPI document object describing the new value of this relationship.
   @return {Promise<record>} A promise that resolves with the new value in this belongs-to relationship.
   */


  push(objectOrPromise) {
    return Ember.RSVP.resolve(objectOrPromise).then(data => {
      var record; // TODO deprecate data as Model

      if (data instanceof Model) {
        record = data;
      } else {
        record = this.store.push(data);
      }

      assertPolymorphicType(this.internalModel, this.belongsToRelationship.relationshipMeta, record._internalModel, this.store); //TODO Igor cleanup, maybe move to relationship push

      this.belongsToRelationship.setCanonicalRecordData(recordDataFor(record));
      return record;
    });
  }
  /**
   `value()` synchronously returns the current value of the belongs-to
   relationship. Unlike `record.get('relationshipName')`, calling
   `value()` on a reference does not trigger a fetch if the async
   relationship is not yet loaded. If the relationship is not loaded
   it will always return `null`.
    Example
    ```javascript
   // models/blog.js
   export default DS.Model.extend({
      user: DS.belongsTo({ async: true })
    });
    let blog = store.push({
      data: {
        type: 'blog',
        id: 1,
        relationships: {
          user: {
            data: { type: 'user', id: 1 }
          }
        }
      }
    });
   let userRef = blog.belongsTo('user');
    userRef.value(); // null
    // provide data for reference
   userRef.push({
      data: {
        type: 'user',
        id: 1,
        attributes: {
          username: "@user"
        }
      }
    }).then(function(user) {
      userRef.value(); // user
    });
   ```
    @method value
   @return {DS.Model} the record in this relationship
   */


  value() {
    var store = this.parentInternalModel.store;

    var resource = this._resource();

    if (resource && resource.data) {
      var inverseInternalModel = store._internalModelForResource(resource.data);

      if (inverseInternalModel && inverseInternalModel.isLoaded()) {
        return inverseInternalModel.getRecord();
      }
    }

    return null;
  }
  /**
   Loads a record in a belongs to relationship if it is not already
   loaded. If the relationship is already loaded this method does not
   trigger a new load.
    Example
    ```javascript
   // models/blog.js
   export default DS.Model.extend({
      user: DS.belongsTo({ async: true })
    });
    let blog = store.push({
      data: {
        type: 'blog',
        id: 1,
        relationships: {
          user: {
            data: { type: 'user', id: 1 }
          }
        }
      }
    });
   let userRef = blog.belongsTo('user');
    userRef.value(); // null
    userRef.load().then(function(user) {
      userRef.value() === user
    });
   ```
    You may also pass in an options object whose properties will be
   fed forward. This enables you to pass `adapterOptions` into the
   request given to the adapter via the reference.
    Example
    ```javascript
   userRef.load({ adapterOptions: { isPrivate: true } }).then(function(user) {
     userRef.value() === user;
   });
   ```
    ```app/adapters/user.js
   export default ApplicationAdapter.extend({
     findRecord(store, type, id, snapshot) {
       // In the adapter you will have access to adapterOptions.
       let adapterOptions = snapshot.adapterOptions;
     }
   });
   ```
    @method load
   @param {Object} options the options to pass in.
   @return {Promise} a promise that resolves with the record in this belongs-to relationship.
   */


  load(options) {
    return this.parentInternalModel.getBelongsTo(this.key, options);
  }
  /**
   Triggers a reload of the value in this relationship. If the
   remoteType is `"link"` Ember Data will use the relationship link to
   reload the relationship. Otherwise it will reload the record by its
   id.
    Example
    ```javascript
   // models/blog.js
   export default DS.Model.extend({
      user: DS.belongsTo({ async: true })
    });
    let blog = store.push({
      data: {
        type: 'blog',
        id: 1,
        relationships: {
          user: {
            data: { type: 'user', id: 1 }
          }
        }
      }
    });
   let userRef = blog.belongsTo('user');
    userRef.reload().then(function(user) {
      userRef.value() === user
    });
   ```
    You may also pass in an options object whose properties will be
   fed forward. This enables you to pass `adapterOptions` into the
   request given to the adapter via the reference. A full example
   can be found in the `load` method.
    Example
    ```javascript
   userRef.reload({ adapterOptions: { isPrivate: true } })
   ```
    @method reload
   @param {Object} options the options to pass in.
   @return {Promise} a promise that resolves with the record in this belongs-to relationship after the reload has completed.
   */
  // TODO IGOR CHECK FOR OBJECT PROXIES


  reload(options) {
    var resource = this._resource();

    if (resource && resource.links && resource.links.related) {
      return this.store._fetchBelongsToLinkFromResource(resource, this.parentInternalModel, this.belongsToRelationship.relationshipMeta, options);
    }

    if (resource && resource.data) {
      if (resource.data && (resource.data.id || resource.data.clientId)) {
        var internalModel = this.store._internalModelForResource(resource.data);

        if (internalModel.isLoaded()) {
          return internalModel.reload(options).then(internalModel => {
            if (internalModel) {
              return internalModel.getRecord();
            }

            return null;
          });
        } else {
          return this.store._findByInternalModel(internalModel, options);
        }
      }
    }
  }

}
```

**Comment by efx** [comment]
@villander I think @ef4 meant the error debug log: `/var/folders/0v/jpdg1flj3qscvbvt728pgt8c0000gn/T/error.dump.f9e550f228f39a54667691efaab0d6b6.log`

**Comment by villander** [comment]
@efx sure, I'll get it, thank you.

**Comment by stefanpenner** [comment]
semi related: https://github.com/embroider-build/embroider/issues/48

**Comment by stefanpenner** [comment]
Poking at this one now

**Comment by stefanpenner** [comment]
I think the issue is in some path rewriting:
the issue seems to be some pre-processing that is missing: 

working (without embroider)
```
-private/system/references/has-many.js
2:import { assertPolymorphicType } from 'ember-data/-debug';

-private/system/references/belongs-to.js
1:import { assertPolymorphicType } from 'ember-data/-debug';

-private/system/relationships/state/belongs-to.js
1:import { assertPolymorphicType } from 'ember-data/-debug';

-private/system/relationships/state/has-many.js
1:import { assertPolymorphicType } from 'ember-data/-debug';
 s/e/data/D/[/B/ / / ember-data] ╍{}+
```

not-working (without embroider)

```
 ember-data]/-private/system/references/belongs-to.js
3:import { assertPolymorphicType } from "../../../-debug";

 ember-data]/-private/system/references/has-many.js
4:import { assertPolymorphicType } from "../../../-debug";

 ember-data]/-private/system/relationships/state/belongs-to.js
7:import { assertPolymorphicType } from "../../../../-debug";

 ember-data]/-private/system/relationships/state/has-many.js
7:import { assertPolymorphicType } from "../../../../-debug";
```


stew.log occurred [here](https://github.com/emberjs/data/blob/5dcf47ea6f20a3342dda083c7c44c2fb40dd8241/index.js#L110)

**Comment by stefanpenner** [comment]
gotta run, but will continue to debug.

**Comment by stefanpenner** [comment]
Alright, continuing now:

Looks like https://github.com/emberjs/data/blob/722da7ce75597735f1769a98875fcadccb4b8749/index.js#L96 seems to be where we are getting the relative paths during the embroider builds

**Comment by stefanpenner** [comment]
Further debugging, it looks like the embroider build introduces an additional babel plugin, this plugin appears to be causing the above relative paths.

```js
/Users/spenner/src/embroider-build/embroider/packages/core/src/babel-plugin.js
```

**Comment by stefanpenner** [comment]
likely here: https://github.com/embroider-build/embroider/blob/master/packages/core/src/babel-plugin.ts#L16

Debugging...

**Comment by stefanpenner** [comment]
Ok, so I believe the issue is as follows:

ember-data has `ember-data/-debug`

**Comment by ef4** [comment]
Thanks, that makes sense.

The term "external" here is getting overloaded, so we should be clear. `ember-data/-debug` is "external" only in the sense that the Rollup run is supposed to ignore it. But it's truly still internal to ember-data the NPM package, so from Embroider's perspective it's _not_ an external and it can't be.

Arguably, we could be safer from this class of bug if we ran babel twice instead of once, such that our import rewriting happens after any custom broccoli trees have finished (those custom broccoli trees already invoke babel, which is why we would then have two runs of babel).

But I'm not really inclined to add that complexity and cost. For one thing, we can't entirely stop modifying the babel config that is invoked by the custom broccoli trees anyway, because we definitely need to neuter things like presets and module compilation. For another, I think what ember-data is doing here is a bad idea anyway.

We should fix by adding a compatAdapter that neuters the whole custom treeForAddon. The treeForAddon does three things:

  1. it adds a version number module
  2. it ensures that the debug code is only included sometimes
  3. it tries to hide private modules by rolling them up

Items 1 and 2 will still be needed. Item 3 is actively harmful, in that it's hiding modules from our stage3 and preventing us from shaking unused ones out.

**Comment by stefanpenner** [comment]
>  For another, I think what ember-data is doing here is a bad idea anyway.

Yup.

> We should fix by adding a compatAdapter that neuters the whole custom treeForAddon.

My thoughts as well.


---

Note: I did the root cause, for 2 reasons:

* make sure I understand what embroider is doing my own insight
* confirm that there is no deeper bug in embroider. (So far, it seems like we can help guide ember-data to a better future long term, and short-term implement the adapter you mentioned).

**Comment by stefanpenner** [comment]
@runspired pointed out that ember-data is planning a larger build refactor: https://github.com/emberjs/rfcs/pull/395 we should be aware.

**Comment by runspired** [comment]
In the packages world there will be an explicit `@ember-data/debug` package so it will be a `"true”` external dependency from the `npm` perspective.  I don't disagree with that aspect of what we are doing being bad today, it was just necessary given the state of available CLI tools and transforms when the infra was put in place.

In terms of our `rollup` usage being actively harmful more generally, I most definitely disagree and I hope there continues to be support for libraries to define how their modules are built.

What our rollup step does in order of importance is

- allows for better code organization within a set of code that is otherwise best represented as a single module
- prevents unintended leaking of private utils and classes
- optimizes that module
- eliminates dead code within that module

Specifically, it isn’t hiding modules: user’s of ember-data should never be aware of these internal structures.

Nor is it preventing tree-shaking: there is nothing within it that tree-shaking would be capable of dropping. Where there eventually could be, we intend to move the code into it’s own package (one purpose of packages RFC) however there is sadly almost no sub-package of ember-data that could be tree-shaken even once packages work completes until additional work is completed. Specifically:

1) RFC changes to default adapter and serializer setup and eliminate automatic wiring of the provided adapters and serializers as fallbacks
2) RFC elimination of `DS.Model.toJSON`
3) get rid of `defaultStore` in `Ember`
4) get rid of eager initializers in ember-data
5) convert features in secondary packages into dynamic imports so that they can be dropped if unused.

We want to unlock this, but it’ll take work and is not something that embroider can magically give anyone for free. Even with the packages RFC we should still make use of the rollup strategy for building `-private` modules within our packages: **the value-add of limiting our surface area of leaked capabilities is just too high.**

**Comment by stefanpenner** [comment]
> @ember-data/debug

Ya, this as a separate module would totally negate the motivating issue

> allows for better code organization within a set of code that is otherwise best represented as a single module
> prevents unintended leaking of private utils and classes

I think "private" or "mangled" modules is a useful idea, but long-term hiding this from the "final stage packager" does sound like an anti-pattern.

> optimizes that module

Did we end up getting measurements from this?

> eliminates dead code within that module

One of the stretch goals of the late state packager is DCO, so again, short-term likely nothing bad, but long-term we should aim to have the LSP be sufficiently advanced to handle these needs.
