### ISSUE TITLE
Double template transform in nested addon

### ISSUE THREAD

**Issue by jrjohnson** [embroider-build/embroider#403]
I think this is more universal than [ember-simple-set-helper](https://github.com/pzuraq/ember-simple-set-helper) which contains a template transform so I'm opening it here.

`app` -> `addon` -> `ember-simple-set-helpers`

If you use that transform in an addon you have to include `ember-simple-set-helper` as a `dependency` and not a `devDependency` or it doesn't work in the consuming app. However, in that case building the addon with `embroider` seems to run the template transformation twice. For `ember-simple-set-helper` this results in an error [from here](https://github.com/pzuraq/ember-simple-set-helper/blob/7c78f861204c67692b59f4502144389f371e372b/lib/simple-set-transform.js#L31).

`Error: the (set) helper can only recieve 2 arguments at most, recieved: 3`

Reproduction at https://github.com/jrjohnson/reproduction-embroider-simple-set-addon
Just run `npm start` to see the error.

This may be what @ef4 is referring to in https://github.com/embroider-build/embroider/issues/392#issuecomment-587559020 if that's the case I'm not sure how to contribute to testing embroider until an addon format is finalized, but that seems too late.

**Comment by jrjohnson** [comment]
Updated the reproduction to the latest everything and still seeing this issue with double transforming the template in an addon.

**Comment by ef4** [comment]
When doing the complete app build, Embroider intentionally uses a single template compiler for the whole app and all addons. This is different from the traditional build, which has a separate template compiler for each package. This means that transformations installed by the app can see addon code.

What's happening here is:
 - the addon's code gets transformed in stage1 (the compatibility layer), because all later stages need to be in v2 format which intentionally doesn't support addons installing their own custom transforms. 
 - the app (a dummy app in this case) also happens to have the same AST transform installed, and that transform will see *all* code, including the already-transpiled addon.

So everything is working as intended here.

My suggestion is to change the transform so it's less fragile. Transforms should be pure functions of their input, and their input and output types must both contain all valid HBS. Another way to say that is: 

 - the output of a transform needs to be legal HBS
 - users are allowed to type any legal HBS
 - therefore the code emitted by a transform needs to be legal as the input of the transform too.

It's easy to fix by using different names for the pre-transpiled and post-transpiled forms. `{{set this.foo "bar"}}` would transform to `{{-set this "foo" "bar"}}`, and then there's no problem. (Or any other name, I just picked `-set` because that's been the convention for private helpers in HBS.) Or if there's a reason why the runtime name really wants to still be `set`, an alternative *explicit* marker can be compiled in, like an additional named argument.

**Comment by ef4** [comment]
I would also add that until Ember ships a solution for all helpers being global, using an addon in an addon that claims a common name like `set` is kinda problematic.

**Comment by jrjohnson** [comment]
Thanks for this explanation @ef4 I'm going to pursue a PR to change the transform to: `{{-set this "foo" "bar"}}` as that seems like a clean solution.

> I would also add that until Ember ships a solution for all helpers being global, using an addon in an addon that claims a common name like set is kinda problematic.

Yes, agreed, in a public addon - but we use and addon to consolidate some components that are available in multiple apps. Which I don't think is terribly uncommon so I wanted to add that detail here.
