### ISSUE TITLE
Does this compile standalone glimmer components?

### ISSUE THREAD

**Issue by konradjurk** [embroider-build/embroider#422]
The following guideline uses Ember CLI to make a glimmer component available as a WebComponent but I am a bit confused as to whether or not embroider can be used to accomplish that:
https://glimmerjs.com/guides/using-glimmer-as-web-components 

Thanks! :)

**Comment by ef4** [comment]
It is probably possible but not without making some changes to the glimmerjs app's build pipeline. 

Most likely, you can just jettison most of `@glimmerjs/application-pipeline`, because a lot of what's in there is trying to do an embroider-like thing.

I don't have more detailed instructions than that, at the moment this would be an exploratory project for whoever is interested.

**Comment by konradjurk** [comment]
@ef4  Thank you, I'll have a look and reopen in case I encounter a problem ^^
