### ISSUE TITLE
Addon asset namespacing collisions

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#5]
https://github.com/embroider-build/embroider/blob/master/SPEC.md#assets mentions that assets from addons get namespaced. What happens if the addon is included twice in the build with different versions?

**Comment by ef4** [comment]
Since writing that I've actually implemented, and it turned out that achieving the namespacing for all legacy addons is not really possible, so I've relaxed the rules somewhat. It's now closer to how things already work today, where addon authors are trusted to pick names with low probability of collision.

I think for the public assets this is acceptable, since their public URLs are important and can't always be changed, and are therefore a true point of contention that needs to get dealt with explicitly.
