### ISSUE TITLE
Addons using ember-cli-typescript@4 do not get their TypeScript transpiled

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/embroider#528]
We discovered this while testing a new version of ember-a11y-testing that uses `ember-cli-typescript@4`. During the Embroider build the `.ts` files (located in `addon-test-support`) are not transpiled into `.js` in Embroider's working directory.

I'm making a tracking issue here so we can work towards a solution...

**Comment by rwjblue** [comment]
/cc @chriskrycho @dfreeman (for visibility)

@scalvert - Can you share repro steps? Or plausibly make a small Embroider demo app that has the issue?

**Comment by scalvert** [comment]
Yep. Will push up a repro repo right now :)

**Comment by scalvert** [comment]
https://github.com/scalvert/a11y-embroider-repro/tree/broken

**Comment by chriskrycho** [comment]
Interesting. I believe Embroider at some point had some special handling for ember-cli-typescript, which should no longer be required – I’ll start by looking there tomorrow or Thursday if @dfreeman or @jamescdavis don’t get there first.

**Comment by dfreeman** [comment]
I'm not super familiar with the implementation details of Embroider, but at a glance this looks suspicious: https://github.com/embroider-build/embroider/blob/2842a3482119a38bed32d9fc7b8050922b46efdf/packages/compat/src/v1-addon.ts#L202:L207

Since `ember-cli-typescript` no longer adds any explicit plugins to the Babel config, this conditional will no longer get tripped if an addon doesn't have other plugins set up. The TS plugin (and `.ts` extension) are now handled within `ember-cli-babel` itself [if `ember-cli-typescript` >= 4 is present or `enableTypeScriptTransform` is set](https://github.com/babel/ember-cli-babel/pull/314).

**Comment by jamescdavis** [comment]
The repro doesn't have `ember-a11y-testing` as a dep. 😃  After adding `ember-a11y-testing@4.0.0-beta.1`, I was able to repro the issue. The problem has to do with detecting when an addon (but not the host app) uses ember-cli-typescript@4 and setting up Babel. I was able to get things working for the repro by tweaking things in `@embroider/compat`. I'll put a PR up soon.

**Comment by jamescdavis** [comment]
@dfreeman, yep that's part of it. https://github.com/embroider-build/embroider/compare/master...jamescdavis:e-c-ts-4-addon-fix gets the repro passing, at least.

**Comment by ef4** [comment]
Thanks for testing and reporting, I reviewed #529 with commentary so we can get to the bottom of this.

**Comment by scalvert** [comment]
@jamescdavis oops I forgot to add `ember-a11y-testing`. Can add it and push.

**Comment by scalvert** [comment]
Added.
