### ISSUE TITLE
Using Embroider while developing an addon does not rebuild

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/embroider#532]
Steps to reproduce:

1. `npx ember-cli addon foo`
2. `cd foo`
3. `npm install --save-dev @embroider/core @embroider/compat @embroider/webpack`
4. Update `ember-cli-build.js` to use Embroider:

```diff
diff --git a/ember-cli-build.js b/ember-cli-build.js
index dc5a39e..81a5031 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -7,12 +7,6 @@ module.exports = function(defaults) {
     // Add options here
   });
 
-  /*
-    This build file specifies the options for the dummy test app of this
-    addon, located in `/tests/dummy`
-    This build file does *not* influence how the addon or the app using it
-    behave. You most likely want to be modifying `./index.js` or app's build file
-  */
-
-  return app.toTree();
+  const { Webpack } = require('@embroider/webpack');
+  return require('@embroider/compat').compatBuild(app, Webpack);
 };
```

5. Write some code in `addon/**`
6. `ember serve`
7. Update code in `addon/**`
8. No updates

---

To simplify, I've made a [small demo repo](https://github.com/rwjblue/___test-embroider-in-addon-development):

1. `git clone git@github.com:rwjblue/___test-embroider-in-addon-development.git`
2. cd `___test-embroider-in-addon-development`
3. `npm ci`
4. `ember s`
5. Edit `addon/helpers/say-something.js`, notice no updates

**Comment by ef4** [comment]
Thanks for reporting, I see this too, I thought we *had* fixed this already but either we didn't or we regressed.

There is a workaround -- embroider is aware of the the broccoli feature flag `BROCCOLI_ENABLED_MEMOIZE=true` and if it's set, all addons are allowed to rebuild as needed (because that flag makes doing so not unreasonably expensive).

But yeah, we need to make sure that when building a dummy app, the dummy app's owning addon is always allowed to rebuild.

**Comment by ef4** [comment]
Oh, also you can explicitly give embroider a list of addons that you want to rebuild by passing a comma-separated list in the `EMBROIDER_REBUILD_ADDONS` environment variable.

**Comment by rwjblue** [comment]
Thanks!
