### ISSUE TITLE
Support for mapping args to component usage in compat resolver

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#558]
In ember-bootstrap I have still an API present - which obviously stems from a time way before embroider - which allows form components to specify their control type, which get rendered by a dedicated component. Simplified example:

```hbs
<BsForm as |form|>
  <form.element @controlType="checkbox" />
  <form.element @controlType="power-select" />
</BsForm>
```

So in this example the first control element is rendered by the `bs-form/element/control/checkbox` component. while the second by `bs-form/element/control/power-select` (amongst other things like layout, label, error components etc.)

Though there is a fundamental difference between these two: the checkbox is a built-in component, and with the latest refactoring to support Embroider with `staticComponents`, embroider is able to understand that it is used [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.hbs#L84).

The second though is provided by an additional [addon](https://github.com/kaliber5/ember-bootstrap-power-select), and used by some [dynamic lookup mechanism](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.js#L780-L789), which embroider is not able to understand of course.

An obvious way to rewrite this would be to explicitly pass the control component in a statically analyzable way, like:
 
```
  <form.element @controlComponent={{component "bs-form/element/control/power-select"}} />
```

This would already work, however this makes it quite verbose to use, and requires a bigger refactoring for existing usage. Also I believe any kind of form abstraction library might like to use similar dynamic patterns for ease of use. Quick emberobserver search found [this](https://github.com/nibynic/ember-form-builder/blob/master/addon/components/form-builder/input.hbs#L4) in ember-form-builder...

So I wonder if we should just always strive for statically analyzable code out of the box, eventually with a somewhat decreased DX as given in the example above, or provide some escape hatches to make embroider aware of certain dynamic usage?

For the latter we already have the instrument of dependency rules, but AFAICT the pattern described here is not yet supported. I believe it should be possible to add support for such a rule in some way, but not sure if we really *should*.

@ef4 thoughts?

**Comment by ef4** [comment]
I think this isn't really an embroider-specific question so much as trying to make sure Ember itself is going in the direction we need it to go. Two already-merged RFCs are relevant here:

1. [strict mode](https://github.com/emberjs/rfcs/blob/ba5ce1b78c8778de344b2fb16e24af18e5fcdcfd/text/0496-handlebars-strict-mode.md) templates won't support any dynamic resolution at all. So your example would change to something like this

    ```hbs
   import PowerSelect from "bs-form/element/control/power-select";
   ---
   <form.element @controlComponent={{PowerSelect}} />
    ```

   (That RFC doesn't finalize the import syntax, but it's implied that *something* will need to bring a component into scope before you can talk about it. )

2. [named blocks](https://github.com/emberjs/rfcs/blob/2e7463135c37c22fbe0588c32bb47d2a09e8a0d5/text/0460-yieldable-named-blocks.md) give you new ways of composing components. You can make callers of `<form.element>` do their own invocation of the controlComponent:

    ```hbs
    <form.element>
      <:control>
        <PowerSelect />
      </control>
    </form.element>
    ```

     which has other benefits too, like letting users set both HTML attributes and arguments on the control component, without learning any special syntax.

All that said, if you want to support a limited possible set of components and don't mind including them all even when they're not used, that is relatively straightforward. It can even use pattern matching, because your component's JS can do:

```js
class extends Component {
  get controlComponent() {
    return importSync(`./inputs/${this.args.which}`);
  }
}
```
```hbs
<this.controlComponent />
```

(I'm assuming here it's possible to import a component into JS and then invoke it in your template. That doesn't actually work right now, but is another thing that necessarily must work before strict mode can be a thing.)

But if you want the unused components to not end up in the app, I do think you need to define the API so that users need to actually invoke or import or `{{component ...}}` the one that is getting used.

**Comment by simonihmig** [comment]
Thanks for taking the time to go into details here! 

> named blocks give you new ways of composing components. You can make callers of <form.element> do their own invocation of the controlComponent:

Yes, in fact you can already do that. Just not with named blocks, but simple block invocation. But the mentioned API was meant to allow for a terse invocation, basically allowing a pluggable architecture that treats built-in control types the same as external ones, from the point of the user. But I guess in a world of explicitness over dynamism, this idea does not fit in really well anymore...

> All that said, if you want to support a limited possible set of components and don't mind including them all even when they're not used, that is relatively straightforward. 

Maybe I have a misunderstanding of what `importSync()` does, but I thought it just requires a module dynamically, but it will not ensure those modules are actually part of the final bundle, will it? Like in your example, if you have `.inputs/tel` and `./inputs/email` components, but you never *statically* import them or use them in a statically analyzable way in a template invocation, they will not make their way into the final bundle, so that `importSync()` call for e.g. `@which="tel"` will fail, right?

So let's say we accept that an addon's component will be included even if unused, how would you ensure that? 

> But if you want the unused components to not end up in the app, I do think you need to define the API so that users need to actually invoke or import or {{component ...}} the one that is getting used.

Yeah, I will probably concentrate on that. As I said in the first post, I felt unsure if we should actually try to support that type of dynamism, as it felt as a step backwards given the direction Ember and Embroider are heading to. Thanks for confirming!
