### ISSUE TITLE
Thoughts on release automation?

### ISSUE THREAD

**Issue by rwjblue** [embroider-build/embroider#585]
I've been thinking that it may make sense to add some sort of release automation here to make it easier to do things like change log curation and updating GitHub releases (I don't think we currently do this, but its **really** nice for folks that want to watch this repo for "releases only").

I'm happy to whip up a PR to use my "go to" setup (basically `npx create-rwjblue-release-it-setup`). 

[Here is the general release documentation for it.](https://github.com/rwjblue/create-rwjblue-release-it-setup/blob/master/RELEASE.md)

What do you think?

**Comment by simonihmig** [comment]
:+1: would love it! I am using Rob's setup basically everywhere nowadays!

**Comment by ef4** [comment]
Yeah, this sounds good, as long as your tool can update all the cross dependencies between packages. I didn’t use lerna because it has bit me in the past and keeping everything in lock step, at least right now, is enough. 

Pretty soon though we will want to cut a stable release of (for example), the macros package. At which point fancier release management may be required, as not everything will stabilize at the same time.

**Comment by ef4** [comment]
It may also be fine to let macros graduate to a separate repo.
