### ISSUE TITLE
Tree-shaking for code in /app not working

### ISSUE THREAD

**Issue by simonihmig** [embroider-build/embroider#589]
I have this [reproduction app](https://github.com/simonihmig/embroider-playground) that shows a couple of issues with the way modules are distributed across chunks, which basically boils down to code in the `/app` folder not being tree-shaken as one would expect.

The app does the following things:
* the `foo` route renders a `foo` component
* the `bar` route renders a `bar` component
* the `addon` route renders an external addon's component (Bootstrap button)
* clicking the above button should lazy load the `/app/lazy.js` module through a dynamic import
* there is a `unused` component and a `/app/unused.js` simple module
* the app is configured with the most aggressive settings ( `static*` all `true`)

## First run: *without* route-based code splitting

When commenting out [this line](https://github.com/simonihmig/embroider-playground/blob/master/ember-cli-build.js#L33) to disable `splitAtRoutes`, you get these results: 

✅  `foo` route renders a `foo` component
✅  `bar` route renders a `bar` component
✅  `addon` route renders addon's button component
✅  dynamically importing the `lazy.js` module resolves the correct module
❌  dynamically importing the `lazy.js` module loads a new chunk lazily
❌  the `lazy.js` module is not contained in any of the base chunks (`<script>` in `index.html`)
❌   the `unused` component is not contained in any chunk
❌   the `unused.js` module is not contained in any chunk
✅  unused components of the addon are not contained in any chunk

## Second run: *with* route-based code splitting

✅  `foo` route renders a `foo` component
✅  transitioning to `foo` lazy loads a new chunk
✅  that chunk contains the route's class and template
❌  that chunk contains the `foo` component (see #470)
❌  the `foo` component is not contained in any of the base chunks (`<script>` in `index.html`)

✅  `bar` route renders a `bar` component
✅  transitioning to `bar` lazy loads a new chunk
✅  that chunk contains the route's class and template
❌  that chunk contains the `bar` component (see #470)
❌  the `bar` component is not contained in any of the base chunks (`<script>` in `index.html`)

✅  `addon` route renders addon's button component
✅  transitioning to `addon` lazy loads a new chunk
✅  that chunk contains the route's class and template
✅  that chunk contains the `bs-button` component (*actually two separate chunks, which ideally should be only one!?)
✅  the `bs-button` component is not contained in any of the base chunks (`<script>` in `index.html`)

✅  dynamically importing the `lazy.js` module resolves the correct module
❌  dynamically importing the `lazy.js` module loads a new chunk lazily
❌  the `lazy.js` module is not contained in any of the base chunks (`<script>` in `index.html`)
❌   the `unused` component is not contained in any chunk
❌   the `unused.js` module is not contained in any chunk
✅  unused components of the addon are not contained in any chunk

## Conclusions

It seems as if the old bundling behavior of ember-cli is de-facto still present, i.e. everything in `/app` is going into the (base) bundles unconditionally, whether the modules are used or not. Only for external modules (coming from an addon) we can see the bundling behavior we expect.

**Comment by ef4** [comment]
Thanks for sharing the reproduction, it was helpful. There was a real bug here, but not all of what you're describing above is a bug.

The bug was our handling of co-located templates, which were indeed always being included in the main bundle.

But `app/lazy.js` is never going to be lazy. By virtue of being under `/app` and being a file that we can't categorize (as a component, helper, route, etc), it will always end up in the build. Changing that is going to require going beyond `@embroider/compat` and defining a new app authoring format where *everything* is strict, and that will depend on Ember eliminating the need for runtime resolution out of the app tree in general.

If you really have a file in your app that you want to only ever load statically, when it's needed, you can put it in an in-repo-addon's `addon` folder. Then as long as `staticAddonTrees` is enabed, it will only get included if it's imported.

**Comment by simonihmig** [comment]
> The bug was our handling of co-located templates, which were indeed always being included in the main bundle.

Great that you could fix this quickly, thanks!

> The bug was our handling of co-located templates, which were indeed always being included in the main bundle.

Ok, got it. 

I understand that you can use an in-repo addon, but that's not really that convenient. Would it be possible to have some folder like `/lib` not being part of `/app`, thus not falling under this include-everything category, but still allow to have modules there that you can (dynamically) import?

I should explain my use case a bit more, maybe there is some alternative that I am completely missing. So I want to lazy load stuff from a large library. `const myModule = await import('large-npm-package`);` wouldn't work, as that would import all of that library's code, while I only need some (tree-shaken) named exports.

So I want to use `lazy.js` as the entrypoint that webpack sees to create a new chunk, so I can `import('lazy')` and have `lazy.js` import (and re-export) only the things I need. This would give me a single webpack chunk, which contains only the named exports (and other code that these depend on) that `lazy.js` imports from `large-npm-package`, right?

Again, I can totally use an in-repo addon as an escape hatch, but wonder if a pattern like that is that unusual that we can justify needing this Ember-specific workaround?

**Comment by ef4** [comment]
This is all about workarounds until we can reform the actual app format itself. Right now, the simplest, safest way to ensure you don't load a large library until it's needed is to rely on the route splitting to do it for you. 

Probably it's OK to give app authors a new embroider option that controls which patterns under app are considered static only. You can see the existing categorization [here](https://github.com/embroider-build/embroider/blob/64cf75bfd220b493dea31f1d08b33d79c8b840f9/packages/core/src/app-files.ts). The modules in `components`, `helpers` and `perRoute` get their own specific handling, controlled by `staticComponents`, `staticHelpers` and `splitAtRoutes` respectively. Everything else goes into `otherAppFiles`, and that category is always included [by this code](https://github.com/embroider-build/embroider/blob/64cf75bfd220b493dea31f1d08b33d79c8b840f9/packages/core/src/app.ts#L985-L991).

That would be enough to let certain arbitrary files shake out of the app when they are unused. But it's not enough for your use case, because you also want `import()` within an app's own package.

I've been careful not to let "classic apps" and "embroider apps" diverge into two different formats. **There is only one format**, until such a time as we do an RFC and make a new embroider-only format. But that means if we're going to allow `import()` of code within the app, we need a story for how that works in classic builds. That would mean extending ember-auto-import so that it can take over parts of the app's own code. It's not clear there's a mode where that works, short of it actually just becoming full embroider.

So I'm deliberately not making it super convenient to do things that work under embroider but break under classic builds.

**Comment by simonihmig** [comment]
Makes sense, thank you! I'll go for the in-repo approach for now.
