### ISSUE TITLE
Webpack resolve alias doesn't work

### ISSUE THREAD

**Issue by mwasilewski** [embroider-build/embroider#662]
My ember-cli-build.js has this (I tried without autoImport config too):
 
 ```
 module.exports = function(defaults) {

  let app = new EmberApp(defaults, {

    autoImport: {
      alias: {
        'utils': path.join(__dirname, 'app', 'utils')
      }
    },
    babel: {
      plugins: [require.resolve('ember-auto-import/babel-plugin')]
    }
  });

  const { Webpack } = require('@embroider/webpack');

  return require('@embroider/compat').compatBuild(app, Webpack, {
    staticAddonTestSupportTrees: true,
    staticAddonTrees: true,
    staticHelpers: true,
    staticComponents: true,
    packagerOptions: {
      webpackConfig: {
        resolve: {
          alias: {
            'utils': path.join(__dirname, 'app', 'utils')
          }
        }
      }
    }
  });
};
```

and then trying to import doesn't work:

```
import constants from 'utils/constants';
```

```
router.js:1212 Error while processing route: app.index Could not find module `utils/constants` imported from `(require)`
```

**Comment by mwasilewski** [comment]
test repo is here, only one commit added to fresh ember app: https://github.com/mwasilewski/embroider-alias-problem/commit/09e733abb6c74d4439cac0698dcaf9804037f029

**Comment by ef4** [comment]
App code is still always authored in v1 format (as that term is defined in the embroider RFC). That means it needs quite a bit of massaging before we can hand it off to webpack. Part of that massaging involves us trying to resolve all imports and converting any missing ones into runtime `window.require` instead. That happens before webpack sees the code, so webpack-specific resolving rules like this don't have a chance to handle it.

I don't think we should solve this by teaching Embroider to use webpack's resolving rules, because we're trying to keep the core of embroider agnostic to specific bundlers. Rather, we should probably move toward supporting emerging standards like Node's [subpath imports](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_subpath_imports) or [exports](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_exports). The hope is that all other tooling (typescript, linters, bundlers) will also understand these.

I will also point out that your ember-auto-import config:

```js
autoImport: {
     alias: {
       'utils': path.join(__dirname, 'app', 'utils')
     }
   },
```

probably results in code duplication in your build (when not using embroider, and instead relying on ember-auto-import), because everything under `app` is already getting included by the standard build, and if you make ember-auto-import also include it, you'll get it and all its dependencies a second time.

**Comment by mwasilewski** [comment]
in other words, there is no workaround for this right, now, and I should be using relative paths at the moment?

**Comment by ef4** [comment]
There are other ways to do this, like [babel-plugin-module-resolver](https://www.npmjs.com/package/babel-plugin-module-resolver).

But IMO it's nicer to just use the app's package name, because that tells readers where the code is really coming from without them needing to hunt through your config files. If you create `/app/utils.js`, you can import it from anywhere in the app via `import "my-app-name/utils"`. This works under both classic and embroider builds.

**Comment by mwasilewski** [comment]
that's what I needed - use app's package name - thanks!
