### ISSUE TITLE
Error when trying to run tests: unsupported module was defined

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#677]
> Uncaught Error: an unsupported module was defined, expected `define(id, deps, module)` instead got: `1` arguments to define` at http://localhost:7357/assets/vendor.js, line 64

https://github.com/simplabs/qunit-dom/pull/970 is trying to update the embroider dependency in qunit-dom, but it fails with the above error and `ember test` ultimately timing out.

The stack trace of the error is pointing to https://github.com/emberjs/ember-test-helpers/pull/958 being the problem. It looks like the `es6-promise` import there is not working correctly.

Note that this only happens in combination with the new ember-qunit v5 setup. With ember-qunit v4 this is not an issue because the test-helpers PR above was only added in v2.x, which is not used by ember-qunit v4.

/cc @rwjblue @ef4

**Comment by ctjhoa** [comment]
Looks like I have a very similar issue on this PR:
https://github.com/zestia/ember-select-box/pull/32

The weird thing is: 
- if I run `CI=true node_modules/.bin/ember try:one embroider-safe` => build is KO
- if I run without the `CI` env variable `node_modules/.bin/ember try:one embroider-safe` => build is fine

Here is an example of build failure:
https://travis-ci.org/github/zestia/ember-select-box/jobs/765467368

```
node : v10.24.0
@ember/test-helpers : 2.2.5
ember-qunit : 5.1.4
@embroider/test-setup: ^0.39.1
@embroider/util: ^0.39.1
```

**Comment by ef4** [comment]
This is due to https://github.com/embroider-build/embroider/issues/731#issuecomment-808788950

You can use embroider's `skipBabel` option to workaround.

```js
skipBabel: [
  {
    package: 'qunit',
  },
],
```

**Comment by mansona** [comment]
I'm getting a similar error but I have tried the `skipBabel` trick 🤔 

Here is the error: https://github.com/mansona/ember-cli-notifications/pull/308/checks?check_run_id=2332566153#step:5:80 and here is where we added the `skipBabel` https://github.com/mansona/ember-cli-notifications/pull/308/commits/cf9057e152938c3d1535b64ee2c320afd7f480a4

Am I missing something? 🤔

**Comment by ctjhoa** [comment]
In @mansona case,
there was a missing dependency to `ember-auto-import`.
https://github.com/mansona/ember-cli-notifications/pull/310

**Comment by simonihmig** [comment]
I pulled my hairs out because of this, as everything was working fine locally, but only failing in CI. Turned out I forgot (once again) that you would need to set `CI=true` locally to actually replicate what's happing in CI. 🤦‍♂️. Glad I found this issue here now, but took me a while...

I think we need to prevent this experience from happening for other users:
* should we add the `skipBabel` config to the default blueprint for addons [here](https://github.com/ember-cli/ember-cli/blob/master/blueprints/addon/files/ember-cli-build.js#L18)?
* or should `maybeEmbroider()` handle this implicitly, by enforcing that config internally for qunit. Or maybe just when it detects IE in the targets of the `app` that is passed to it?

**Comment by rwjblue** [comment]
@simonihmig - Ya, I think we should make the addon blueprint do the same as the app blueprint

https://github.com/ember-cli/ember-cli/blob/dae8449a4035144df423661385c6902f2ce7911b/blueprints/app/files/ember-cli-build.js#L24-L29

**Comment by stefanpenner** [comment]
es6-promise is also effected by this

**Comment by Turbo87** [comment]
not sure what exactly solved this, but it appears to work fine now for crates.io
