### ISSUE TITLE
Rebuild not working with ember-intl (translation file changes will be ignored)

### ISSUE THREAD

**Issue by mkszepp** [embroider-build/embroider#718]
When i add/edit a translation file from [ember-intl](https://github.com/ember-intl/ember-intl) (example: my-project/translations/en.json) the rebuild is not starting.
There is always necessary to stop an restart the `ember s`.

No errors in output.

Tested on Linux + Windows

OS: Linux
Ember Cli: 3.25.2
Embroider: 0.37.0
Ember Intl: 5.6.2

OS: Windows 10 x64
Ember Cli: 3.25.2
Embroider: 0.29.0 (newer version are not working on windows - see https://github.com/embroider-build/embroider/issues/681)
Ember Intl: 5.6.2

Steps to reproduce:
1. `npm install -g ember-cli`
2. `ember new test-app`
3. `npm i @embroider/core @embroider/compat @embroider/webpack`
4. edit `ember-cli-build.js` (specified in Readme.md)
5. `ember install ember-intl` + required file changes (see [ember-intl quickstart](https://ember-intl.github.io/ember-intl/docs/quickstart))
6. `ember s`
7. modify a translation file

**Comment by ef4** [comment]
It looks like ember-intl considers your translations part of itself (they live inside it's own module namespace instead of the app's).

Try setting the environment variable `EMBROIDER_REBUILD_ADDONS=ember-intl`. That will probably work around this problem.

ember-intl should consider refactoring so that translations stay in the app's module namespace.

**Comment by mkszepp** [comment]
@ef4 thank you, i can confirm, that the work around works for me.
