### ISSUE TITLE
WARNING: Your build is slower because some babel plugins are non-serializable []

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#72]
```
Building into /private/var/folders/6y/_8qpkt114jzb442txt_9w_2c0000gn/T/embroider-cjbPbI
WARNING: Your build is slower because some babel plugins are non-serializable []
```

I suppose the above warning was supposed to include the names of the plugins that are not serializable, but apparently this was not the case. Is there another way to find out what went wrong here?

**Comment by ef4** [comment]
Some of this is self-inflicted right now, because some of our own AST transforms are not serializable. (AST transforms are not babel plugins, but they do need to run inside the inline-hbs babel plugin, so their serializability matters.)

We definitely need a better message here though, because even once we fix our own there will still be cases where users have non-serializable plugins.

One way to check what is causing the problem is to inspect `_babel_config_.js` and `_template_compiler_.js` in the intermediate build directory (the directory name prints on the console as "Building into..." at the start of the build). Anything in those files that says:

```
{
  "embroiderPlaceholder": true,
  "type": "global",
}
```

is encoding a non-serializable value.

**Comment by villander** [comment]
How fix this @ef4 ?

![image](https://user-images.githubusercontent.com/10222774/54850121-01901980-4cc5-11e9-80a5-0a64f2a9935e.png)

**Comment by ef4** [comment]
I see what's causing that one, it's a silly bug in PortablePluginConfig. We're treating "undefined" as not serializable.

**Comment by ef4** [comment]
The example that @villander shared above is fixed. And the things I mentioned in my first comment are also fixed.

This issue is still open because it would still be better to have a more actionable message here.

**Comment by villander** [comment]
thanks @ef4 🚀

**Comment by villander** [comment]
@ef4 I continue getting this warning - `WARNING: Your build is slower because some babel plugins are non-serializable` 

You fixed it , but the message keep yet on `v0.3.4`?

**Comment by ef4** [comment]
I fixed all the internal things that would cause the message. It's still a legitimate warning if your app has some transforms that are not parallelizable.

One common cause ember-cli-template-lint, which prior to v1.0.0-beta.3 would generate this error.

**Comment by villander** [comment]
I'm using ember-cli 3.9.0 with `"ember-cli-template-lint": "^1.0.0-beta.1"`

**Comment by NullVoxPopuli** [comment]
Given that this is for embroider < v1, I'm going to close.

If the same issue exists on current embroider (v3.2+), let's open a new issue. thanks all!
