### ISSUE TITLE
[@embroider/util] Invalid dependency on broccoli-funnel

### ISSUE THREAD

**Issue by chriseppstein** [embroider-build/embroider#764]
https://github.com/embroider-build/embroider/blob/master/packages/util/package.json#L32

This dependency spec isn't pointing to released software but is included in the released version of `@embroider/util` at version `0.39.1`.

This causes issues importing software into LinkedIn's artifact cache but I suspect it will cause other issues as well.

**Comment by ef4** [comment]
I'm glad LinkedIn wants to fix this because LinkedIn broke it. 😝  

Specifically, the refactor that happened in broccoli-funnel 3.0 broke [this behavior that embroider relies on](https://github.com/broccolijs/broccoli-funnel/pull/136). I already found and fixed [another serious bug](https://github.com/broccolijs/broccoli-funnel/pull/135) in that release. 

And I couldn't stay on 2.x because 2.x depends on an old walk-sync with [a critical bug](https://github.com/joliss/node-walk-sync/pull/40) that is fixed in the walk-sync version used by broccoli-funnel 3.0.

Please get broccoli-funnel 3.x fixed and I will gladly switch back to a published version.

**Comment by chriseppstein** [comment]
@ef4 I'm just here to let you know that embroider releases can no longer be consumed by linkedin because of this issue. If you were to publish your forked code under a released package e.g. `@ef4/broccoli-funnel` then it would allow embroider releases to be consumed again. I'll ping @rwjblue about this issue in hopes that we can find a fast resolution. Thanks.
