### ISSUE TITLE
[Discussion] Does embroider do dependency pre-bundling like ViteJS does ?

### ISSUE THREAD

**Issue by siva-sundar** [embroider-build/embroider#788]
Just trying out embroider for some of our apps. Bit curious to know whether embroider does some kind of dependency pre-bundling(like vitejs) to speed up the server startup time.

**Comment by ef4** [comment]
That's not a feature that would belong in Embroider itself, because Embroider is not a Javascript bundler. It delegates to a Javascript bundler, after compiling away Ember-specific conventions and backward-compatibility problems. Embroider can use [Vite](https://github.com/embroider-build/embroider/pull/759), though that is not yet as polished as using it with webpack.

**Comment by siva-sundar** [comment]
Thanks for the response!

>  It delegates to a Javascript bundler, after compiling away Ember-specific conventions and backward-compatibility problems.

Just curious to know whether we could apply pre-bundling for this compilation part.

**Comment by ef4** [comment]
Yes, the goal is to get all addons to ship in the new v2 format, which means they will be pre-built by their authors down to the standard format and won't need any preprocessing by embroider at all.

I would add that the dependency pre-building step in Vite (and Snowpack) is a cost, not a benefit, of that build architecture. It's mostly needed because so many dependencies still ship as CommonJS and not ES modules. It would be better not to need it and instead get library authors to directly ship a minimal set of ES modules.
