### ISSUE TITLE
Route.render not working

### ISSUE THREAD

**Issue by maxymczech** [embroider-build/embroider#824]
It seems that each Route is only aware of its own template. When I try to render another template with `this.render(...)` in `renderTemplate` hook, I get

> Error: Assertion Failed: Could not find "..." template, view, or component

I have `splitAtRoutes` enabled.

**Comment by ef4** [comment]
Yes, using `this.render` to dynamically change the template or controller is not compatible with `splitAtRoutes` and there is no plan to support it. It is pretty fundamentally dynamic and can't be statically analyzed. I'm honestly a little surprised `this.render` isn't deprecated, I think that's only because nobody has been able to prioritize time to write the deprecation RFC.

I can suggest three possible paths forward for you so you can achieve route splitting.

## Re-align with conventions using reexports

If you were using a hard-coded template that just happens to not match your route name, like:

```js
// app/routes/first.js
this.render('second');
```

You can replace that by deleting `this.render()` and creating `app/templates/second.js` containing `export { default } from './first'`. Then the structure is clear to embroider and cannot dynamically change.

## Refactoring dynamic template choices

If instead you're picking the template on the fly:

```js
this.render(useFirst() ? 'first' : 'second');
```

then you will need to refactor to move that logic down into the template itself and move the existing templates into components:

```js
{{#if this.usefirst}}
  <First />
{{else}}
  <Second />
{{/if}}
```

This option is probably the most work, if there's a lot of complexity in your controllers.

## Manually load templates as runtime

As a workaround, your route can manually import and register with ember the template it's going to need:

```js
// app/routes/first.js
import Route from '@ember/routing/route';

export default class ApplicationRoute extends Route {
  async beforeModel() {
    let templateName = pickCustomNameHere();
    let template = await import(`../templates/${templateName}`);
    window.define(`your-app-name/templates/${templateName}`, () => template);
  }

  renderTemplate() {
      this.render(pickCustomerNameHere());
  } 
}
```

This has some caveats:

1. Dynamically importing code out of the app itself only works under embroider, you can't switch back to a classic non-embroider build, so that can make a smooth transition harder. 
2. Relying directly on `window.define` is likely to break in a future release. From embroider's perspective, the whole AMD loader is legacy technology. But realistically it will probably stick around for a while in most apps.

**Comment by maxymczech** [comment]
Thank you for detailed response. I have already started going with second option - moving logic from controller to a component and using that in specific routes.

**Comment by SergeAstapov** [comment]
> I'm honestly a little surprised `this.render` isn't deprecated, I think that's only because nobody has been able to prioritize time to write the deprecation RFC.

Actually it was deprecated and will be removed in Ember.js 4.0 per RFC https://emberjs.github.io/rfcs/0418-deprecate-route-render-methods.html

**Comment by kategengler** [comment]
I think this can be closed since `render` is no longer supported.
