### ISSUE TITLE
App code generation

### ISSUE THREAD

**Issue by Turbo87** [embroider-build/embroider#9]
There are a few addons that attempt to generate code across code type boundaries; e.g. they analyze templates and generate JS files from the information. In the current system these things are quite complicated and limited due to various constraints. Is the new system designed to ease these problems?

**Comment by ef4** [comment]
Yes. I think those cases are difficult today because:

 - the current build is factored by _topic_ (build all the templates, then build all the JS, then build all the styles) rather than by _package_ (build everything in ember-power-select, then build everything in ember-data, then build everything in the app).

 - there is no reliable global rule for addressing and resolving things in the build. 

This design changes both of those factors. We design the build so that each package can be built in isolation. And once your dependencies are compiled into v2, you can always resolve any of the things you depend on by following normal node_modules rules.
