### ISSUE TITLE
Addons with components/services not registered in global namespace tests fail under embroider-optimized

### ISSUE THREAD

**Issue by cah-briangantzler** [embroider-build/embroider#969]
In an addon you can opt out of exposing your components and services to the global namespace by deleting the appropriate files in the app folder. This way you will not pollute the global namespace of the app and remove conflicts of other addons that may have the same component/service name as you. 

In the app you would refer to the service as 
```
@service('MyAddon@MyService')
myService;
```

or a component in hbs via 
```
<MyAddon@MyComponent ... >
```

When running the addon tests the it would look like 
```
  test('it exists', function(assert) {
    let service = this.owner.lookup('service:EmbroiderTestNamespace@TestService');
    assert.ok(service);
  });
```

This test runs under all modes except embroider-optimized.     

What needs to be done to get this test to execute under embroider-optimized?

Here is a thread where this little known but extremely handy capability is talked about https://github.com/kaliber5/ember-stargate/pull/9 where @rwjblue comments.

Here is a repo  https://github.com/bgantzler/embroider-test-namespace I have created you can just clone and run the tests using ember-try. You will see all tests pass except embroider-optimized.

**Comment by ef4** [comment]
I would encourage addons not to rely on this. Supporting it requires us to disable tree shaking for *all* addon trees, because we can't tell which thing you might decide to resolve at runtime via `@`. Mostly it works fine for us to *not* support this because the pattern is thankfully not common.

Instead, for private components, helpers, or modifiers I would encourage addons to directly import them:

```js
// addon/a-public-component.js
import APrivateComponent from './-private/whatever';
export default class APublicComponent extends Component {
  whatever = APrivateComponent;
}
```

```hbs
// addon/a-public-component.hbs
<this.whatever />
```

This works for any component that has a co-located template, on Ember 3.25+. If you want it to work on older Ember you can use the ensureSafeComponent function from `@embroider/util`. 

It's also aligned with the [Strict Mode RFC](https://github.com/emberjs/rfcs/blob/master/text/0496-handlebars-strict-mode.md).

For services, Ember doesn't really give us a better alternative yet. It will need one if we ever want services to be route-splittable. For the present, my recommendation is to continue using a reexport in the `app` tree. You can literally name the module so you get the same level of "namespacing" as with the `@`, just choosing one character differently:

```js
```

**Comment by cah-briangantzler** [comment]
Thanks for the help
