### ISSUE TITLE
Watching additional file extensions

### ISSUE THREAD

**Issue by NullVoxPopuli** [embroider-build/embroider#972]
I'm using a markdown -> ember generator (Docfy), and noticed that under embroider, changes to markdown files do not cause rebuilds.

- Is there something I, as an app dev, can change to my build to make embroider watch markdown files?
- Is there something Docfy can do (as an addon), to enable consuming apps to watch markdown files?

**Comment by NullVoxPopuli** [comment]
I think the same problem exists with ember-intl -- I need to restart my server to see changes in the *.yaml files

**Comment by ef4** [comment]
I don't think this is a question of file extensions. 

This is usually because an addon is emitting some of your app's code from within the addon's broccoli hooks, which means from embroider's perspective that code is part of the addon and the addon is not under development so it doesn't get rebuilds.

Try setting the env var `EMBROIDER_REBUILD_ADDONS=@docfy/ember,ember-intl`. If that fixes it, this was the issue.

For now these addons can document that that's required to get rebuilds. Ultimately, they need to stop trying to take over the build pipeline and instead become preprocessors (or in webpack terminology, loaders).

**Comment by NullVoxPopuli** [comment]
that works, thanks!

cc @josemarluedke :D

**Comment by lifeart** [comment]
Could we have it in readme if not exists?
